Repository kmesh-net/kmesh, pull requests merged in 2023-12, with the labels that each got.

#60 mini-test adapt
  test/testcases/kmesh/libs/cni.conflist
  test/testcases/kmesh/libs/common.sh
Labels: bug

#68 fix :can't obtain cluster config when image start up
  build/docker/kmesh.yaml
Labels: lgtm, approved, size/XS

#67 kmesh readme optimization
  README-zh.md
  README.md
  docs/pics/logo/KMESH-horizontal-colour.png
  docs/pics/logo/KMESH-stacked-colour.png
Labels: size/M

#69 Promote code owners as per community membership
  OWNERS
Labels: size/XS
