Repository kmesh-net/kmesh, pull requests merged in 2024-02, with the labels that each got.

#106 Intree proto apis
  .github/workflows/main.yml
  .gitignore
  Makefile
  api/Makefile
  api/v2-c/admin/config_dump.pb-c.c
  api/v2-c/admin/config_dump.pb-c.h
  api/v2-c/cluster/circuit_breaker.pb-c.c
  api/v2-c/cluster/circuit_breaker.pb-c.h
  api/v2-c/cluster/cluster.pb-c.c
  api/v2-c/cluster/cluster.pb-c.h
  api/v2-c/core/address.pb-c.c
  api/v2-c/core/address.pb-c.h
  api/v2-c/core/base.pb-c.c
  api/v2-c/core/base.pb-c.h
  api/v2-c/endpoint/endpoint.pb-c.c
  api/v2-c/endpoint/endpoint.pb-c.h
  api/v2-c/filter/http_connection_manager.pb-c.c
  api/v2-c/filter/http_connection_manager.pb-c.h
  api/v2-c/filter/tcp_proxy.pb-c.c
  api/v2-c/filter/tcp_proxy.pb-c.h
  api/v2-c/listener/listener.pb-c.c
  api/v2-c/listener/listener.pb-c.h
  api/v2-c/listener/listener_components.pb-c.c
  api/v2-c/listener/listener_components.pb-c.h
  api/v2-c/route/route.pb-c.c
  api/v2-c/route/route.pb-c.h
  api/v2-c/route/route_components.pb-c.c
  api/v2-c/route/route_components.pb-c.h
  api/v2/admin/config_dump.pb.go
  api/v2/cluster/circuit_breaker.pb.go
  api/v2/cluster/cluster.pb.go
  api/v2/core/address.pb.go
  api/v2/core/base.pb.go
  api/v2/endpoint/endpoint.pb.go
  api/v2/filter/http_connection_manager.pb.go
  api/v2/filter/tcp_proxy.pb.go
  api/v2/listener/listener.pb.go
  api/v2/listener/listener_components.pb.go
  api/v2/route/route.pb.go
  api/v2/route/route_components.pb.go
  go.mod
  go.sum
  hack/gen-check.sh
  hack/install-proto.sh
Labels: kind/enhancement, lgtm, approved, size/XXL

#114 fix kmesh start failed, cannot connect to istiod
  build/docker/clusterrolebinding.yaml
  pkg/cni/chained.go
Labels: lgtm, approved, size/XS

#101 Support build kmesh from container #76
  Makefile
  build.sh
  build/docker/kmesh.dockerfile
  build/docker/kmesh.yaml
  build/docker/start_kmesh.sh
  kmesh_compile.sh
Labels: lgtm, approved, size/L

#110 improve ads of kmesh
  .github/workflows/main.yml
  build.sh
  build/docker/kmesh.yaml
  config/kmesh.json
  docs/kmesh_commands-zh.md
  docs/kmesh_commands.md
  go.mod
  go.sum
  pkg/controller/config.go
  pkg/controller/envoy/ads_client.go
  pkg/controller/envoy/ads_config.go
  pkg/controller/interfaces/client.go
  pkg/nets/connect.go
Labels: lgtm, approved, size/XL

#115 modify kmesh_compile.sh to suit different arch
  kmesh_compile.sh
Labels: kind/enhancement, lgtm, approved, size/S

#120 fix misconfig of node.ID
  build/docker/kmesh.yaml
  pkg/controller/envoy/ads_config.go
Labels: kind/bug, lgtm, approved, size/XS

#121 Add helm deploy
  README-zh.md
  README.md
  deploy/README.md
  deploy/helm/.helmignore
  deploy/helm/Chart.yaml
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/daemonset.yaml
  deploy/helm/templates/kmesh-rbac.yaml
  deploy/helm/templates/serviceaccount.yaml
  deploy/helm/values.yaml
  deploy/yaml/clusterrole.yaml
  deploy/yaml/clusterrolebinding.yaml
  deploy/yaml/kmesh.yaml
  deploy/yaml/serviceaccount.yaml
Labels: kind/enhancement, lgtm, approved, size/L

#123 fix:helm install kmesh failed
  deploy/helm/templates/daemonset.yaml
Labels: lgtm, approved, size/XS

#124 Fix the issue that the kmesh-cni plugin is not mounted in workload m…
  pkg/cni/install.go
Labels: kind/bug, approved, size/XS

#98 add the design of kmesh support workload model
  docs/proposal/kmesh_support_workload.md
  docs/proposal/pics/delete_workload.svg
  docs/proposal/pics/kmesh_workload_subscribe.svg
  docs/proposal/pics/new_workload.svg
  docs/proposal/pics/traffic_governance.svg
  docs/proposal/pics/update_workload.svg
Labels: lgtm, approved, size/L

#125 Specifying Kmesh startup parameters during Helm installation
  deploy/helm/templates/daemonset.yaml
  deploy/helm/values.yaml
Labels: kind/enhancement, approved, size/XS

#127 Sync Image Tags Between Helm Chart and Registry
  deploy/helm/values.yaml
Labels: kind/bug, lgtm, approved, size/XS

#130 Added default image hub target and tag
  Makefile
Labels: kind/bug, lgtm, approved, size/S

#129 cleanup tmp modified files
  .gitignore
  Makefile
  bpf/kmesh/bpf2go/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/kmeshcgroupsockworkload_bpfel.go
  kmesh_compile.sh
Labels: kind/enhancement, lgtm, approved, size/L

#132 The YAML adapted for version 0.2.0
  deploy/helm/values.yaml
  deploy/yaml/kmesh.yaml
Labels: lgtm, approved, size/XS

#131 Adapting the release documentation for kmesh v0.2.0
  README-zh.md
  README.md
  build/docker/README.md
  deploy/README.md
  docs/kmesh_compile-zh.md
  docs/kmesh_compile.md
  docs/multiple dataplane_CN.md
  docs/multiple dataplane_EN.md
Labels: lgtm, approved, size/XL

#139 Demonstrate UT coverage in CI
  .github/workflows/main.yml
Labels: kind/enhancement, lgtm, approved, size/XS
