Repository kmesh-net/kmesh, pull requests merged in 2024-09, with the labels that each got.

#783 Optimize endpoint index getter and also rename some methods to be mor…
  pkg/controller/workload/bpfcache/endpoint.go
  pkg/controller/workload/bpfcache/factory.go
  pkg/controller/workload/cache/workload_cache.go
  pkg/controller/workload/cache/workload_cache_test.go
  pkg/controller/workload/workload_controller.go
  pkg/controller/workload/workload_hash.go
  pkg/controller/workload/workload_hash_test.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: kind/enhancement, lgtm, approved, kind/cleanup, size/XL

#800 fix verifier log omitted
  pkg/bpf/bpf.go
  pkg/bpf/bpf_kmesh_l4_workload.go
Labels: lgtm, approved, size/S

#807 Optimize service frontend map delete: by using existing service addre…
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: lgtm, approved, size/M

#809 make codecov as an indication
  .codecov.yml
Labels: lgtm, approved, size/XS

#803 Batch update metrics through prometheus API
  go.mod
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
  pkg/controller/telemetry/utils.go
  pkg/controller/telemetry/utils_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#801 update kubeconfig when token was updated
  daemon/manager/manager.go
  daemon/manager/uninstall/uninstall.go
  daemon/options/cni.go
  go.mod
  pkg/cni/chained.go
  pkg/cni/chained_test.go
  pkg/cni/install.go
  pkg/cni/install_test.go
  pkg/cni/kubeconfig.go
Labels: kind/enhancement, lgtm, approved, size/L

#813 ci: add helm target
  Makefile
  README-zh.md
  deploy/README.md
  deploy/charts/kmesh-helm/.helmignore
  deploy/charts/kmesh-helm/Chart.yaml
  deploy/charts/kmesh-helm/templates/_helpers.tpl
  deploy/charts/kmesh-helm/templates/daemonset.yaml
  deploy/charts/kmesh-helm/templates/kmesh-rbac.yaml
  deploy/charts/kmesh-helm/templates/l7-envoyfilter.yaml
  deploy/charts/kmesh-helm/templates/serviceaccount.yaml
  deploy/charts/kmesh-helm/values.yaml
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/M

#808 Refactor workload.Services compare and eliminate `shouldAddEndpoint`
  pkg/controller/workload/bpfcache/backend.go
  pkg/controller/workload/bpfcache/endpoint.go
  pkg/controller/workload/bpfcache/frontend.go
  pkg/controller/workload/bpfcache/service.go
  pkg/controller/workload/cache/workload_cache.go
  pkg/controller/workload/cache/workload_cache_test.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: lgtm, approved, size/L

#712 do rbac in xdp prog
  api/v2-c/Makefile
  bpf/include/bpf_common.h
  bpf/kmesh/ads/include/kmesh_common.h
  bpf/kmesh/bpf2go/bpf2go.go
  bpf/kmesh/workload/include/authz.h
  bpf/kmesh/workload/include/config.h
  bpf/kmesh/workload/include/workload.h
  bpf/kmesh/workload/include/workload_common.h
  bpf/kmesh/workload/include/xdp.h
  bpf/kmesh/workload/xdp.c
  pkg/auth/policy_store.go
  pkg/auth/policy_store_test.go
  pkg/auth/rbac_test.go
  pkg/bpf/bpf_kmesh_l4_workload.go
  pkg/bpf/bpf_kmesh_workload.go
  pkg/cache/v2/maps/authz.go
  pkg/controller/workload/bpfcache/auth_policy.go
  pkg/controller/workload/bpfcache/fake_map.go
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/workload/workload_processor.go
Labels: lgtm, approved, size/XL

#831 typo
  samples/fortio/netutils.yaml
Labels: kind/bug, lgtm, approved, size/XS

#830 cleanup unuse parameters
  pkg/controller/manage/manage_controller.go
Labels: lgtm, approved, kind/cleanup, size/XS

#810 add doc for startup of eBPF program
  docs/Startup_process_of_eBPF_programs.md
  docs/dataplane_forward.md
  docs/pics/dataplane_forward.png
  docs/pics/kmesh-attach-point.png
  docs/pics/startup_process_of_eBPF_programs.png
Labels: lgtm, approved, size/M

#832 increase timeout of bookinfo e2e test
  test/e2e/baseline_test.go
Labels: kind/enhancement, lgtm, approved, size/XS

#836 cgo: using CC=clang and CXX=clang++
  Makefile
Labels: lgtm, approved, size/XS

#833 Add more approvers
  pkg/OWNERS
  test/OWNERS
Labels: lgtm, approved, size/S

#817 update golangci lint
  common/config/.golangci.yaml
  pkg/controller/security/caclient_test.go
  pkg/controller/security/manager_test.go
  pkg/controller/workload/workload_processor.go
  pkg/dns/dns.go
Labels: lgtm, approved, size/S

#695 Filter out unhealthy workloads
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: lgtm, approved, kind/feature, size/M

#834 update confusing get workload logging
  pkg/auth/rbac.go
  pkg/controller/telemetry/metric.go
Labels: lgtm, approved, size/XS

#796 some cleanups and rename on start type
  daemon/manager/manager.go
  pkg/bpf/bpf.go
  pkg/bpf/bpf_restart.go
  pkg/bpf/bpf_restart_test.go
Labels: lgtm, approved, kind/cleanup, size/M

#842 fix crash when waypoint is not network address type
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: kind/bug, lgtm, approved, size/M

#846 Support passing VERSION to docker when run make docker
  Makefile
  hack/utils.sh
Labels: kind/enhancement, lgtm, approved, size/XS

#848 Update push-builder-image.yml only run on dockerfile or go dependency…
  .github/workflows/push-builder-image.yml
Labels: lgtm, approved, size/XS

#856 fix clean bpf_map twice in test
  pkg/bpf/bpf.go
  pkg/bpf/bpf_restart_test.go
  pkg/controller/ads/ads_processor_test.go
  pkg/status/status_server.go
  pkg/status/status_server_test.go
  pkg/utils/test/bpf_map.go
Labels: kind/bug, lgtm, approved, size/M

#853 support dump workload bpf map
  pkg/controller/workload/bpfcache/auth_policy.go
  pkg/controller/workload/bpfcache/backend.go
  pkg/controller/workload/bpfcache/common.go
  pkg/controller/workload/bpfcache/endpoint.go
  pkg/controller/workload/bpfcache/fake_map.go
  pkg/controller/workload/bpfcache/frontend.go
  pkg/controller/workload/bpfcache/service.go
  pkg/controller/workload/workload_controller.go
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
  pkg/status/status_server.go
  pkg/status/status_server_test.go
Labels: lgtm, approved, size/L

#814 Fix accesslog
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
Labels: kind/bug, lgtm, approved, size/M

#847 make default logger only print to stderr not file
  daemon/main.go
  daemon/manager/manager.go
  pkg/auth/rbac.go
  pkg/bpf/bpf.go
  pkg/cache/v2/listener.go
  pkg/cache/v2/maps/listener.go
  pkg/cni/install.go
  pkg/cni/plugin/plugin.go
  pkg/controller/ads/ads_controller.go
  pkg/controller/bypass/bypass_controller.go
  pkg/controller/config/config.go
  pkg/controller/controller.go
  pkg/controller/manage/manage_controller.go
  pkg/controller/security/manager.go
  pkg/controller/telemetry/utils.go
  pkg/controller/workload/bpfcache/factory.go
  pkg/controller/workload/workload_controller.go
  pkg/dns/dns.go
  pkg/logger/logger.go
  pkg/status/status_server.go
  pkg/utils/exec.go
Labels: lgtm, approved, size/M

#860 build: fix `make gen` failed on arm64.
  hack/install-proto.sh
Labels: lgtm, approved, size/M

#867 fix ads deserial bug
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
Labels: kind/bug, lgtm, approved, size/S

#854 upgrade protoc and protoc-gen-go
  api/v2/admin/config_dump.pb.go
  api/v2/cluster/circuit_breaker.pb.go
  api/v2/cluster/cluster.pb.go
  api/v2/core/address.pb.go
  api/v2/core/base.pb.go
  api/v2/endpoint/endpoint.pb.go
  api/v2/filter/http_connection_manager.pb.go
  api/v2/filter/tcp_proxy.pb.go
  api/v2/listener/listener.pb.go
  api/v2/listener/listener_components.pb.go
  api/v2/route/route.pb.go
  api/v2/route/route_components.pb.go
  api/v2/workloadapi/security/authorization.pb.go
  api/v2/workloadapi/workload.pb.go
  build.sh
  hack/install-proto.sh
  kmesh_compile_env_pre.sh
Labels: lgtm, approved, size/L

#843 Fix dns memleak when dns cluster removed
  pkg/controller/ads/ads_processor.go
  pkg/controller/ads/ads_processor_test.go
  pkg/dns/dns.go
  pkg/dns/dns_test.go
Labels: lgtm, approved, size/L

#870 remove spammy cni installer log
  pkg/cni/install.go
  pkg/cni/kubeconfig.go
Labels: lgtm, approved, size/XS

#873 Add proposal for local rate limit.
  docs/proposal/local_ratelimit.md
  docs/proposal/pics/local_ratelimit.svg
  docs/proposal/pics/token_bucket_algorithm.png
Labels: lgtm, approved, size/L

#871 add a trigger for accesslog
  daemon/manager/manager.go
  daemon/options/bpf.go
  pkg/controller/client.go
  pkg/controller/client_test.go
  pkg/controller/controller.go
  pkg/controller/telemetry/metric.go
  pkg/controller/workload/workload_controller.go
  pkg/controller/workload/workload_processor_test.go
Labels: approved, size/M

#866 Enable non-default cluster
  test/e2e/run_test.sh
Labels: kind/enhancement, approved, size/S

#865 implement kmeshctl framework
  .gitignore
  Makefile
  ctl/log/log.go
  ctl/main.go
  daemon/manager/log/log.go
  daemon/manager/manager.go
Labels: kind/enhancement, lgtm, approved, size/L

#885 add github ci ignore path
  .github/workflows/e2e-ipv6-istio-1.23.yml
  .github/workflows/e2e-ipv6.yml
  .github/workflows/e2e-istio-1.23.yml
  .github/workflows/e2e.yml
  .github/workflows/main.yml
Labels: lgtm, approved, size/S

#881 use depguard to prohibitate importing github.com/golang/protobuf #876(after rebase)
  common/config/.golangci.yaml
  go.mod
  go.sum
  pkg/controller/ads/cache_test.go
  pkg/controller/ads/convert_filter_test.go
  pkg/controller/config/config.go
  pkg/controller/workload/workload_hash.go
  pkg/dns/dns.go
Labels: lgtm, approved, size/M

#884 optimize kmesh-daemon binary
  daemon/manager/manager.go
Labels: kind/enhancement, lgtm, approved, size/XS

#889 implement `kmeshctl dump`
  ctl/dump/dump.go
  ctl/log/log.go
  ctl/main.go
  ctl/utils/portforwarder.go
  daemon/manager/dump/dump.go
  daemon/manager/manager.go
Labels: kind/enhancement, lgtm, approved, size/L

#874 Build 2 series of eBPF objects(kernel ver. <5.13 & >=5.13) and load eBPF dynamically when Kmesh starts up
  bpf/include/bpf_common.h
  bpf/include/inner_map_defs.h
  bpf/kmesh/ads/include/kmesh_common.h
  bpf/kmesh/ads/include/tail_call_index.h
  bpf/kmesh/bpf2go/bpf2go.go
  config/kmesh_marcos_def.h
  kmesh_macros_env.sh
  pkg/bpf/bpf_kmesh_common.go
  pkg/bpf/bpf_kmesh_workload.go
  pkg/utils/kernel_version.go
Labels: kind/enhancement, lgtm, approved, size/L

#877 Prevent potential panic when object is nil or empty
  pkg/cache/v2/maps/authz.go
  pkg/cache/v2/maps/cluster.go
  pkg/cache/v2/maps/common.go
  pkg/cache/v2/maps/listener.go
  pkg/cache/v2/maps/route.go
Labels: lgtm, approved, size/M

#890 make xds request send async
  pkg/controller/ads/ads_controller.go
  pkg/controller/ads/ads_controller_test.go
  pkg/controller/client.go
  pkg/controller/workload/workload_controller.go
Labels: kind/bug, lgtm, approved, size/L

#827 Support ads bpf map lookup all
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
  pkg/bpf/bpf_kmesh.go
  pkg/bpf/bpf_kmesh_l4.go
  pkg/cache/v2/cluster.go
  pkg/cache/v2/cluster_test.go
  pkg/cache/v2/listener.go
  pkg/cache/v2/listener_test.go
  pkg/cache/v2/maps/authz.go
  pkg/cache/v2/maps/cluster.go
  pkg/cache/v2/maps/listener.go
  pkg/cache/v2/maps/route.go
  pkg/cache/v2/route.go
  pkg/cache/v2/route_test.go
  pkg/status/status_server.go
  pkg/status/status_server_test.go
Labels: lgtm, approved, size/XL

#896 [release-0.5] update VERSION
  Makefile
Labels: lgtm, approved, size/XS

#893 Fix build warning and remove docker pull explicitly
  .gitignore
  build.sh
  hack/utils.sh
  kmesh_compile.sh
Labels: lgtm, approved, size/S, cherrypick/release-0.5

#903 update VERSION to 0.5.0
  Makefile
Labels: lgtm, approved, size/XS

#902 Revert "update VERSION"
  Makefile
Labels: lgtm, approved, size/XS

#610 support large scale for ads mode
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
  bpf/include/bpf_common.h
  bpf/kmesh/ads/include/config.h
  docs/proposal/map-in-map_management_enhancement-en.md
  docs/proposal/pics/map-in-map-elastic-process.svg
  docs/proposal/pics/map-in-map-elastic.svg
  pkg/bpf/bpf.go
Labels: lgtm, approved, do-not-merge/contains-merge-commits, size/XL, cherrypick/release-0.5

#909 cherry-pick #610 to Release 0.5
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
  bpf/include/bpf_common.h
  bpf/kmesh/ads/include/config.h
  docs/proposal/map-in-map_management_enhancement-en.md
  docs/proposal/pics/map-in-map-elastic-process.svg
  docs/proposal/pics/map-in-map-elastic.svg
  pkg/bpf/bpf.go
Labels: lgtm, approved, kind/feature, size/XL

#904 Update kmesh_deploy_and_develop_in_kind.md
  docs/kmesh_deploy_and_develop_in_kind.md
Labels: lgtm, approved, size/XS

#914 Enhanced kernel: Build 2 series of eBPF objects(kernel ver. <5.13 & >=5.13) and load eBPF dynamically when Kmesh starts up
  pkg/bpf/bpf_kmesh.go
Labels: kind/enhancement, lgtm, approved, size/S

#901 `kmeshctl waypoint` framework
  ctl/main.go
  ctl/utils/utils.go
  ctl/waypoint/waypoint.go
  go.mod
Labels: kind/enhancement, lgtm, approved, size/XL

#924 fix slow restart in workload mode
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
  pkg/bpf/bpf.go
  pkg/bpf/bpf_kmesh_l4_workload.go
Labels: kind/bug, lgtm, approved, size/M
