Repository kmesh-net/kmesh, pull requests merged in 2024-05, with the labels that each got.

#290 opt readme
  README.md
  docs/pics/kmesh-arch.svg
Labels: lgtm, approved, size/L

#280 remove duplicate NODE_NAME env
  deploy/helm/templates/daemonset.yaml
  deploy/yaml/kmesh.yaml
Labels: lgtm, approved, size/S

#283 Ignore expected grpc error
  pkg/controller/client.go
  pkg/controller/client_test.go
  pkg/controller/envoy/ads_event.go
  pkg/controller/envoy/ads_event_test.go
  pkg/controller/envoy/ads_stream.go
  pkg/controller/envoy/ads_stream_test.go
  pkg/controller/workload/workload_event.go
  pkg/controller/workload/workload_stream.go
Labels: kind/enhancement, lgtm, approved, kind/cleanup, size/L

#293 Enable merge queue
  .github/workflows/main.yml
Labels: lgtm, approved, size/XS

#287 FIX bpf_map_delete_elem unexpected error log
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/sockops_tuple.c
  oncn-mda/ebpf_src/sock_ops.c
Labels: lgtm, approved, size/S

#299 fix clang format tool not install
  hack/format.sh
Labels: lgtm, approved, size/XS

#301 Kmesh: repair kmesh manager not effect in sockops on oe 23.03
  bpf/kmesh/workload/sockops_tuple.c
Labels: kind/bug, lgtm, approved, size/XS

#303 Kmesh: repair kmesh manager not effect in sockops on oe 23.03
  bpf/kmesh/workload/sockops_tuple.c
Labels: kind/bug, lgtm, approved, size/XS

#286 Fix the issue of incorrect domain matching
  bpf/kmesh/include/route_config.h
Labels: kind/bug, lgtm, approved, size/S, cherrypick/release-0.3

#300 remove unnecessary port fields in frontend_key
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/ctx/sock_addr.h
  bpf/kmesh/workload/include/frontend.h
  bpf/kmesh/workload/include/workload.h
  pkg/controller/workload/bpfcache/frontend.go
  pkg/controller/workload/workload_processor.go
Labels: lgtm, approved, size/L

#302 Add proposal template
  docs/proposal/template.md
Labels: lgtm, approved, size/L

#309 Fix the Enhanced Compilation Failure Issue
  pkg/bpf/bpf_kmesh.go
Labels: lgtm, approved, size/S

#307 apply reviewers and approvers
  OWNERS
Labels: lgtm, approved, size/XS

#311 Currently supporting TCP protocol, add the corresponding checks
  bpf/kmesh/cgroup_sock.c
  bpf/kmesh/workload/cgroup_sock.c
Labels: lgtm, approved, size/XS, cherrypick/release-0.3

#314 [release-0.3] Currently supporting TCP protocol, add the corresponding checks
  bpf/kmesh/cgroup_sock.c
  bpf/kmesh/workload/cgroup_sock.c
Labels: lgtm, approved, size/XS

#312 Fix the Enhanced Compilation Failure Issue
  pkg/bpf/bpf_kmesh.go
Labels: kind/bug, lgtm, approved, size/XS, ok-to-test

#316 add benchmark of workload
  pkg/cache/v2/cluster_test.go
  pkg/cache/v2/listener_test.go
  pkg/controller/ads/ads_processor_test.go
  pkg/controller/client_test.go
  pkg/controller/workload/workload_processor_test.go
  pkg/utils/test/bpf_map.go
Labels: lgtm, approved, size/L

#315 [release-0.3]Fix the issue of incorrect domain matching
  bpf/kmesh/include/route_config.h
Labels: kind/bug, lgtm, approved, size/S

#326 optimization: Accelerates the performance of updating the xDS configuration
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
  bpf/kmesh/include/config.h
  bpf/kmesh/include/kmesh_common.h
  pkg/bpf/bpf.go
Labels: kind/enhancement, lgtm, approved, size/L

#306 add optional of start bypass
  daemon/manager/manager.go
  daemon/options/bypass.go
  daemon/options/options.go
  deploy/helm/values.yaml
  pkg/controller/controller.go
Labels: lgtm, approved, size/M

#328 update listener benchmark
  pkg/cache/v2/listener_test.go
Labels: lgtm, approved, size/XS

#327 Update Readme
  README.md
  docs/pics/advanced-mode.png
  docs/pics/kmesh-advanced-mode.png
  docs/pics/kmesh-arch.png
  docs/pics/simple-mode.png
Labels: lgtm, approved, size/L

#333 only update by_key policy_store for workloadp scope authz
  pkg/auth/policy_store.go
Labels: lgtm, approved, size/XS

#341 fix bpf-map test failed
  pkg/utils/test/bpf_map.go
Labels: kind/bug, lgtm, approved, size/XS

#331 deserialization module optimization
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  docs/proposal/optimizing_bpf_map_update_in_xDS_mode-en.md
  docs/proposal/pics/kmesh-map-in-map-optimization.svg
  docs/proposal/pics/kmesh-map-in-map.svg
  docs/proposal/pics/kmesh-proto.svg
Labels: kind/enhancement, lgtm, approved, kind/cleanup, size/L

#336 fix: should get authz policy from dst-worklod when rbac
  pkg/auth/rbac.go
Labels: lgtm, approved, size/S

#345 Fix some typo errors of some documents
  docs/kmesh_development_guide.md
  docs/multiple dataplane_CN.md
  docs/multiple dataplane_EN.md
Labels: lgtm, approved, size/S

#346 update workload.proto
  api/v2-c/workloadapi/workload.pb-c.c
  api/v2-c/workloadapi/workload.pb-c.h
  api/v2/workloadapi/workload.pb.go
  api/workloadapi/workload.proto
Labels: lgtm, approved, size/XXL

#344 use ztunnel-role with workload mode, fix authz policy not work when update
  pkg/auth/rbac.go
  pkg/controller/ads/ads_processor.go
  pkg/controller/client.go
  pkg/controller/config/config.go
  pkg/controller/config/config_test.go
  pkg/controller/workload/workload_processor.go
Labels: lgtm, approved, size/M

#354 docs: translate xds_handle.md to Chinese
  docs/xds_handle.md
  docs/xds_handle_zh.md
Labels: lgtm, approved, size/M

#357 fix: fix issue template
  .github/ISSUE_TEMPLATE/membership-request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: lgtm, approved, size/XS

#356 feat: support kmesh daemon version command(#198)
  Makefile
  daemon/manager/manager.go
  daemon/manager/version/version.go
  pkg/version/version.go
Labels: lgtm, approved, size/L

#338 fix: make clean does not clean up completely(#264)
  Makefile
Labels: lgtm, approved, size/XS

#305 Added dns resolver proposal
  docs/proposal/dns_resolve.md
  docs/proposal/pics/dns-resolver.svg
Labels: lgtm, approved, size/L

#310 Certificate subscription management module to kmesh
  go.mod
  pkg/constants/constants.go
  pkg/controller/controller.go
  pkg/controller/security/caclient.go
  pkg/controller/security/manager.go
  pkg/controller/security/option.go
  pkg/controller/workload/workload_processor.go
  pkg/nets/connect.go
Labels: lgtm, approved, kind/feature, size/XL

#360 Monitoring code for UT coverage in github CI using codecov
  .github/workflows/main.yml
Labels: lgtm, approved, size/S

#204 add ut of workload_stream.go
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/xdstest/fake_xdsserver.go
Labels: kind/enhancement, lgtm, approved, size/L

#183 add ut of ads_loader.go
  pkg/controller/ads/cache_test.go
Labels: kind/enhancement, lgtm, approved, size/XL

#364 Improve bpf log and bugs fix
  bpf/include/bpf_log.h
  bpf/kmesh/ads/cgroup_sock.c
  bpf/kmesh/ads/include/cluster.h
  bpf/kmesh/ads/include/filter.h
  bpf/kmesh/ads/include/kmesh_common.h
  bpf/kmesh/ads/include/listener.h
  bpf/kmesh/ads/include/route_config.h
  bpf/kmesh/ads/sockops.c
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/workload_common.h
  bpf/kmesh/workload/xdp.c
  pkg/controller/controller.go
Labels: lgtm, approved, kind/feature, size/M

#350 Fix status server panic
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/encoder.h
  bpf/kmesh/workload/sendmsg.c
  bpf/kmesh/workload/sockops_tuple.c
  daemon/manager/manager.go
  docs/pics/fortio_performance_test.png
  pkg/cache/v2/cluster.go
  pkg/cache/v2/listener.go
  pkg/cache/v2/route.go
  pkg/controller/dump/status_server.go
  pkg/status/status_server.go
Labels: lgtm, approved, size/L

#367 Fix cleanup kmesh-cni failed bug
  pkg/cni/chained.go
  pkg/cni/install.go
Labels: kind/bug, lgtm, approved, size/XS

#297 add bypass logic for kmesh
  bpf/include/bpf_common.h
  bpf/kmesh/ads/cgroup_sock.c
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/sockops_tuple.c
  pkg/controller/bypass/bypass_controller.go
Labels: lgtm, approved, size/L

#378 fix: make clean error(#376)
  Makefile
Labels: lgtm, approved, size/XS

#361 some workload mode bugfix and waypoint optimization
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/endpoint.h
  bpf/kmesh/workload/include/frontend.h
  bpf/kmesh/workload/include/service.h
  bpf/kmesh/workload/include/workload.h
  pkg/controller/workload/bpfcache/backend.go
  pkg/controller/workload/bpfcache/service.go
  pkg/controller/workload/workload_processor.go
Labels: lgtm, approved, size/L

#383 Clean kmesh build docker container in make clean
  Makefile
Labels: lgtm, approved, size/XS

#386 docs: optimize deploy/README.md
  deploy/README.md
Labels: lgtm, approved, size/XS

#381 Added instructions on how to become a member of the Kmesh community to the readme.
  CONTRIBUTING.md
Labels: lgtm, approved, size/M

#389 fix picture miss
  docs/pics/fortio_performance_test.png
Labels: lgtm, approved, size/XS

#382 optimization for kmesh build slow
  build/docker/kmesh.dockerfile
  kmesh_compile.sh
Labels: lgtm, approved, size/XS

#368 Improve isManagedWorkload
  pkg/auth/rbac.go
  pkg/auth/rbac_test.go
  pkg/controller/client.go
  pkg/controller/security/manager.go
  pkg/controller/workload/cache/workload_cache.go
  pkg/controller/workload/cache/workload_cache_test.go
  pkg/controller/workload/workload_processor.go
Labels: lgtm, approved, size/L

#385 Support Profiling(#199)
  pkg/status/status_server.go
Labels: lgtm, approved, size/XS

#369 update the workload proposl
  docs/proposal/kmesh_support_workload.md
  docs/proposal/pics/delete_workload.svg
  docs/proposal/pics/new_workload.svg
  docs/proposal/pics/traffic_governance.svg
  docs/proposal/pics/update_workload.svg
Labels: lgtm, approved, size/L

#396 Add automatically docker image push
  .github/workflows/release-master.yaml
Labels: lgtm, approved, size/S

#353 Enable metadata encoder only for waypoint
  bpf/kmesh/bpf2go/bpf2go.go
  bpf/kmesh/workload/sockops.c
  build.sh
  pkg/bpf/bpf_kmesh_workload.go
Labels: lgtm, approved, size/S

#391 add proposal for l4 authz
  docs/proposal/layer4_authorization.md
  docs/proposal/pics/kmesh_l4_authorization.svg
Labels: lgtm, approved, size/M

#398 Fix build docker image in github action
  kmesh_compile.sh
Labels: lgtm, approved, size/XS

#395 unified handing logic for skops->remote_port/local_port
  bpf/include/bpf_common.h
  bpf/include/common.h
  bpf/kmesh/ads/sockops.c
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/sockops.c
  oncn-mda/ebpf_src/sock_ops.c
  oncn-mda/include/mesh_accelerate.h
Labels: lgtm, approved, size/M

#404 Fix dockerimage binary size zero caused by permission
  .github/workflows/release-master.yaml
  build/docker/kmesh.dockerfile
Labels: lgtm, approved, size/S
