Repository kmesh-net/kmesh, pull requests merged in 2024-08, with the labels that each got.

#648 Fixed bug in bpf where IPv4 destination address was stored as IPv6
  bpf/kmesh/workload/sockops.c
  bpf/kmesh/workload/xdp.c
  pkg/auth/rbac.go
  pkg/auth/rbac_test.go
Labels: kind/bug, lgtm, approved, size/M

#657 [Release-0.4] Fix kmesh daemon graceful exit
  build/docker/start_kmesh.sh
  pkg/status/status_server.go
Labels: lgtm, approved, size/S

#658 add some secure compilation options
  Makefile
  api/v2-c/Makefile
  bpf/deserialization_to_bpf_map/Makefile
Labels: lgtm, approved, size/S

#666 fix error log
  pkg/controller/manage/manage_controller.go
  pkg/controller/manage/manage_controller_test.go
Labels: lgtm, approved, size/M

#677 [release-0.4] fix error log that failed to enable Kmesh manage
  pkg/controller/manage/kmesh_manage.go
  pkg/controller/manage/kmesh_manage_test.go
Labels: lgtm, approved, size/M

#661 e2e test for Kmesh daemon restart
  test/e2e/main_test.go
  test/e2e/restart_test.go
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/L

#676 Support ns manage donot need restart pod
  pkg/controller/manage/manage_controller.go
  pkg/controller/manage/manage_controller_test.go
  pkg/utils/enroll.go
Labels: lgtm, approved, size/XL

#659 Fix namespaced waypoint service itself contains waypoint address, cau…
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: lgtm, approved, size/S, cherrypick/release-0.4

#675 Short circuit when svc endpoint count = 0
  bpf/kmesh/workload/include/service.h
Labels: lgtm, approved, size/XS

#673 Update bpf log
  bpf/include/bpf_log.h
Labels: lgtm, approved, size/XS

#682 fix lint
  pkg/controller/manage/manage_controller.go
Labels: kind/bug, lgtm, approved, size/XS

#684 fix data in bpfmap was cleared after kmesh restart in kind env
  bpf/include/bpf_common.h
  pkg/controller/manage/manage_controller.go
Labels: lgtm, approved, size/XS

#686 [release-0.4] Fix namespaced waypoint service itself contains waypoint address
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: kind/bug, size/S

#688 Add service metric and use ringbuf to report metrics
  bpf/kmesh/probes/access_log.h
  bpf/kmesh/probes/metrics.h
  bpf/kmesh/probes/probe.h
  bpf/kmesh/probes/tcp_probe.h
  bpf/kmesh/workload/sockops.c
  docs/proposal/ebpf-observability.md
  pkg/auth/rbac.go
  pkg/auth/rbac_test.go
  pkg/auth/xdp_auth_handler.go
  pkg/constants/constants.go
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
  pkg/controller/telemetry/utils.go
  pkg/controller/telemetry/utils_test.go
  pkg/controller/workload/workload_controller.go
  pkg/controller/workload/workload_processor.go
Labels: kind/enhancement, lgtm, approved, kind/feature, size/XXL, cherrypick/release-0.4

#672 Sync up status API with workload api
  pkg/status/api.go
  pkg/status/testdata/workload_configdump.json
Labels: lgtm, approved, size/M

#690 enable e2e test case for ns granularity waypoint
  test/e2e/baseline_test.go
  test/e2e/main_test.go
Labels: kind/enhancement, lgtm, approved, size/M

#706 fix metric nil pointer panic
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
Labels: kind/bug, lgtm, approved, size/L

#679 Link XDP again in deamon, in order to fix Kmesh has restarted but old XDP program remain linked
  pkg/controller/controller.go
  pkg/controller/manage/manage_controller.go
  pkg/controller/manage/manage_controller_test.go
Labels: kind/bug, lgtm, approved, size/L

#710 [cherry-pick 0.4] add service metrics
  bpf/kmesh/probes/access_log.h
  bpf/kmesh/probes/metrics.h
  bpf/kmesh/probes/probe.h
  bpf/kmesh/probes/tcp_probe.h
  bpf/kmesh/workload/sockops.c
  docs/proposal/ebpf-observability.md
  pkg/auth/rbac.go
  pkg/auth/rbac_test.go
  pkg/auth/xdp_auth_handler.go
  pkg/constants/constants.go
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
  pkg/controller/telemetry/utils.go
  pkg/controller/telemetry/utils_test.go
  pkg/controller/workload/workload_controller.go
  pkg/controller/workload/workload_processor.go
Labels: lgtm, approved, size/XXL

#709 Support hostname network
  api/v2-c/workloadapi/workload.pb-c.c
  api/v2-c/workloadapi/workload.pb-c.h
  api/v2/workloadapi/workload.pb.go
  api/workloadapi/workload.proto
  pkg/controller/workload/cache/workload_cache.go
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: lgtm, approved, size/L

#681 fix waypoint's processing of TCP
  deploy/helm/templates/l7-envoyfilter.yaml
  deploy/yaml/l7-envoyfilter.yaml
  test/e2e/baseline_test.go
  test/e2e/run_test.sh
Labels: kind/bug, lgtm, approved, size/M

#715 Support multi-arch images build and push automatically
  .github/workflows/release-master.yaml
  Makefile
  build/docker/README.md
  build/docker/dockerfile
  build/docker/kmesh.dockerfile
Labels: lgtm, approved, size/L

#719 Update kmesh image
  .github/workflows/release-master.yaml
Labels: lgtm, approved, size/XS

#696 fix bug that may occur in Update mode
  pkg/bpf/bpf.go
  pkg/constants/constants.go
Labels: kind/bug, lgtm, approved, size/M

#722 fix cgroup mount log
  build/docker/start_kmesh.sh
Labels: kind/bug, lgtm, approved, size/XS

#726 Rm coverage threshold
  .codecov.yml
Labels: lgtm, approved, size/XS

#727 use dataplane label to manage workloads
  test/e2e/main_test.go
  test/e2e/manage_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#707 FIX: go test timeout after running benchmark test
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/workload/workload_hash.go
  pkg/controller/workload/workload_hash_test.go
  pkg/controller/workload/workload_processor_test.go
Labels: lgtm, approved, size/S

#731 make bypass idempotent
  pkg/controller/bypass/bypass_controller.go
  pkg/controller/manage/manage_controller.go
  pkg/controller/manage/manage_controller_test.go
  pkg/kube/informer.go
  pkg/utils/exec.go
Labels: lgtm, approved, size/M

#605 support remove residual endpoints
  daemon/manager/manager.go
  pkg/auth/rbac_test.go
  pkg/bpf/bpf.go
  pkg/controller/telemetry/metric_test.go
  pkg/controller/workload/bpfcache/fake_map.go
  pkg/controller/workload/cache/workload_cache.go
  pkg/controller/workload/cache/workload_cache_test.go
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
  pkg/status/status_server_test.go
Labels: kind/bug, lgtm, approved, do-not-merge/contains-merge-commits, size/XL

#729 Update PHONY
  Makefile
Labels: lgtm, approved, size/S

#742 modify dockerfile
  .github/workflows/release-master.yaml
  Makefile
  build/docker/dockerfile
Labels: lgtm, approved, size/M

#743 passthrough go test flag
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/S

#737 fix depolying ns and service waypoint in mixed manner and add related e2e test case
  pkg/controller/workload/workload_processor.go
  test/e2e/baseline_test.go
Labels: kind/bug, lgtm, approved, size/M, cherrypick/release-0.4

#753 Fix image tag
  .github/workflows/release-master.yaml
Labels: lgtm, approved, size/XS

#748 fix ebpf observalility doc
  docs/proposal/ebpf-observability.md
  docs/proposal/pics/probe.svg
Labels: documentation, lgtm, approved, size/M

#754 [cherry-pick 0.4] fix depolying ns and service waypoint in mixed manner
  pkg/controller/workload/workload_processor.go
Labels: kind/bug, lgtm, approved, size/S

#747 match the meaning of Kmesh L4 metric with istio
  pkg/controller/telemetry/utils.go
Labels: lgtm, approved, size/S

#760 Fix: XDP prog duplicate when bpf filesystem mounted
  pkg/bpf/bpf_kmesh_workload.go
Labels: kind/bug, lgtm, approved, size/XS

#617 add kmesh custom grafana addon
  samples/addons/grafana.yaml
  samples/addons/grafana_dashboard.json
Labels: kind/enhancement, lgtm, approved, size/XXL

#772 fix image ci bug:kmesh latest cannot use
  kmesh_compile.sh
Labels: kind/bug, lgtm, approved, size/XS

#759 add e2e test case for cross ns access
  test/e2e/manage_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#717 Bump cilium/ebpf
  build/docker/README.md
  daemon/options/bpf.go
  deploy/helm/templates/daemonset.yaml
  deploy/helm/values.yaml
  deploy/yaml/kmesh.yaml
  go.mod
  go.sum
  pkg/bpf/bpf.go
  pkg/bpf/bpf_kmesh.go
  pkg/bpf/bpf_kmesh_common.go
  pkg/bpf/bpf_kmesh_workload.go
Labels: lgtm, approved, size/L

#773 make logs of metric clean up
  pkg/controller/telemetry/metric.go
Labels: lgtm, approved, kind/cleanup, size/XS

#763 fix bpf prog double load
  pkg/bpf/bpf_kmesh_workload.go
Labels: kind/bug, lgtm, approved, size/L

#771 E2e metric
  go.mod
  test/e2e/baseline_test.go
  test/e2e/main_test.go
  test/e2e/manage_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#765 correctly store origin dst addr in map_of_dst_info at ipv4-mapped ipv…
  bpf/kmesh/workload/cgroup_sock.c
Labels: kind/bug, lgtm, approved, size/S

#776 Check codecov but not fail github checks
  .codecov.yml
Labels: lgtm, approved, size/S

#732 add accesslog to enhance obversiblity of kmesh
  bpf/kmesh/probes/tcp_probe.h
  pkg/controller/telemetry/accesslog.go
  pkg/controller/telemetry/accesslog_test.go
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
Labels: kind/enhancement, lgtm, approved, kind/feature, size/L

#792 update version
  Makefile
Labels: lgtm, approved, size/XS

#790 e2e test to include bookinfo as test application
  test/e2e/baseline_test.go
Labels: kind/enhancement, lgtm, approved, size/M

#723 Improve cni uninstall
  build/docker/start_kmesh.sh
  daemon/manager/manager.go
  daemon/manager/uninstall/uninstall.go
  pkg/cni/chained.go
  pkg/cni/install.go
Labels: lgtm, approved, size/M

#804 Fix possible panic in loadKmeshSendmsgObjects
  pkg/bpf/bpf_kmesh_workload.go
Labels: kind/bug, lgtm, approved, size/XS

#805 fix version display
  Makefile
Labels: lgtm, approved, size/XS
