Repository kmesh-net/kmesh, pull requests merged in 2024-11, with the labels that each got.

#1009 ut: fix local ratelimit code cause other failed.
  pkg/controller/ads/cache.go
  pkg/controller/ads/extensions/local_ratelimit.go
  pkg/controller/ads/extensions/local_ratelimit_test.go
Labels: lgtm, approved, size/S

#968 A constant map is used to pass constants
  bpf/include/bpf_log.h
  bpf/include/common.h
  daemon/manager/manager.go
  pkg/bpf/ads/loader.go
  pkg/bpf/ads/loader_enhanced.go
  pkg/bpf/bpf.go
  pkg/bpf/workload/loader.go
  pkg/status/status_server.go
  pkg/status/status_server_test.go
Labels: lgtm, approved, size/M

#995 handle hostname type waypoint for istio 1.24
  pkg/controller/workload/cache/service_cache.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#997 Add a env flag to allow skip installing dependencies when run ./build.sh
  kmesh_compile_env_pre.sh
Labels: lgtm, approved, size/M

#1019 Update Documentation
  docs/kmesh_compile.md
  docs/kmesh_deploy_and_develop_in_kind.md
Labels: lgtm, approved, size/S

#1017 Some fix about circuit breaker
  bpf/kmesh/ads/include/circuit_breaker.h
  bpf/kmesh/ads/include/ctx/sock_ops.h
Labels: lgtm, approved, size/M

#1003 fix lb_ospp bug and add ref
  pkg/consistenthash/maglev/maglev.go
  pkg/controller/ads/cache.go
Labels: lgtm, approved, size/XS

#971 separation bpf and binary in Makefile&provides bpf2go outputs files
  .github/workflows/main.yml
  .gitignore
  Makefile
  bpf/kmesh/bpf2go/bpf2go.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshtracepoint_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshtracepoint_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshtracepointcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshtracepointcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  build.sh
  hack/gen_bpf2go.sh
  hack/gen_bpf2go_exec.sh
  hack/golangci-lint-prepare.sh
  kmesh_compile_env_pre.sh
  pkg/bpf/ads/sock_connection.go
  pkg/bpf/ads/sock_ops.go
  pkg/bpf/ads/trace_point.go
  pkg/bpf/workload/sendmsg.go
  pkg/bpf/workload/sock_connection.go
  pkg/bpf/workload/sock_ops.go
  pkg/bpf/workload/xdp.go
  pkg/controller/workload/bpfcache/factory.go
  pkg/controller/workload/bpfcache/fake_map.go
  pkg/controller/workload/workload_processor.go
Labels: kind/enhancement, lgtm, approved, do-not-merge/contains-merge-commits, size/XXL

#1002 E2E test for ingress gateway
  hack/copyright-check.sh
  hack/copyright/copyright_scan_dir.json
  test/e2e/gateway_test.go
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/L

#1007 Minor fixes
  daemon/manager/manager.go
  daemon/options/bpf.go
  daemon/options/options.go
  daemon/options/perf.go
  pkg/controller/client.go
  pkg/controller/client_test.go
  pkg/controller/config/config.go
  pkg/controller/controller.go
  pkg/controller/telemetry/bpf_prog_metric.go
  pkg/controller/telemetry/map_metric.go
  pkg/controller/telemetry/utils.go
  pkg/controller/workload/workload_controller.go
  pkg/controller/workload/workload_processor_test.go
  pkg/status/status_server.go
Labels: lgtm, approved, kind/cleanup, size/L

#1013 feat: reduce binary size of kmeshctl
  Makefile
  ctl/accesslog/accesslog.go
  ctl/utils/utils.go
  ctl/waypoint/waypoint.go
  go.mod
  pkg/kube/client.go
  pkg/kube/portforwarder.go
Labels: kind/enhancement, lgtm, approved, size/L

#1018 Ratelimit bug fix.
  bpf/kmesh/ads/include/filter.h
  bpf/kmesh/ads/include/local_ratelimit.h
Labels: lgtm, approved, size/XS

#1040 fix docgen tag
  ctl/gen.go
  docs/ctl/kmeshctl.md
  docs/ctl/kmeshctl_accesslog.md
  docs/ctl/kmeshctl_dump.md
  docs/ctl/kmeshctl_log.md
  docs/ctl/kmeshctl_version.md
  docs/ctl/kmeshctl_waypoint.md
  docs/ctl/kmeshctl_waypoint_apply.md
  docs/ctl/kmeshctl_waypoint_delete.md
  docs/ctl/kmeshctl_waypoint_generate.md
  docs/ctl/kmeshctl_waypoint_list.md
  docs/ctl/kmeshctl_waypoint_status.md
Labels: lgtm, approved, size/S

#1035 Update --profiling flag in kmesh yaml
  deploy/yaml/kmesh.yaml
Labels: lgtm, approved, size/XS

#1038 Fix kmesh_map_count_total label
  pkg/controller/telemetry/map_metric.go
Labels: lgtm, approved, size/XS

#1039 Add more debug log
  bpf/kmesh/probes/probe.h
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/service.h
Labels: lgtm, approved, size/S

#1041 add e2e test for service entry with inlined workload entry
  pkg/controller/workload/workload_processor.go
  test/e2e/baseline_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1043 Keep one Kube client create function
  pkg/bpf/restart/bpf_restart.go
  pkg/cni/plugin/plugin.go
  pkg/controller/config/config.go
  pkg/controller/controller.go
  pkg/kube/informer.go
  pkg/kube/kubeclient.go
  pkg/utils/kubeclient.go
  pkg/utils/nettools.go
Labels: lgtm, approved, size/L

#1045 kmeshctl dump failed issue resolve
  pkg/status/status_server.go
Labels: lgtm, approved, size/XS

#1046 update prometheus image version
  samples/addons/prometheus.yaml
Labels: lgtm, approved, size/XS

#1021 handle hostname type waypoint in workload
  pkg/controller/workload/cache/service_cache.go
  pkg/controller/workload/cache/waypoint_cache.go
  pkg/controller/workload/cache/waypoint_cache_test.go
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: kind/bug, lgtm, approved, size/XL

#1029 optimize xDS bpf map
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
  bpf/include/bpf_common.h
  bpf/include/inner_map_defs.h
  bpf/kmesh/ads/include/circuit_breaker.h
  bpf/kmesh/ads/include/cluster.h
  bpf/kmesh/ads/include/filter.h
  bpf/kmesh/ads/include/listener.h
  bpf/kmesh/ads/include/local_ratelimit.h
  bpf/kmesh/ads/include/route_config.h
  bpf/kmesh/ads/include/tcp_proxy.h
  bpf/kmesh/ads/sockops.c
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  bpf/kmesh/workload/include/authz.h
  pkg/bpf/ads/loader.go
  pkg/bpf/ads/loader_enhanced.go
  pkg/bpf/ads/sock_connection.go
  pkg/bpf/ads/sock_ops.go
  pkg/bpf/bpf.go
  pkg/bpf/utils/bpf_helper.go
  pkg/bpf/workload/loader.go
  pkg/bpf/workload/sock_connection.go
  pkg/bpf/workload/sock_ops.go
  pkg/bpf/workload/xdp.go
Labels: lgtm, approved, size/XXL

#1015 Use bpf map to pass node IP and pod sub gateway. Skip kubelet probe traffic management from ebpf
  bpf/include/bpf_log.h
  bpf/include/common.h
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  bpf/kmesh/workload/sockops.c
  deploy/yaml/clusterrole.yaml
  pkg/bpf/bpf.go
  pkg/bpf/bpf_test.go
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
  pkg/status/status_server.go
Labels: kind/enhancement, lgtm, approved, size/L

#985 support xdp auth in tailcall
  bpf/include/common.h
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  bpf/kmesh/workload/include/authz.h
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/config.h
  bpf/kmesh/workload/include/tail_call.h
  bpf/kmesh/workload/xdp.c
  ctl/authz/authz.go
  ctl/common/common.go
  deploy/charts/kmesh-helm/templates/kmesh-rbac.yaml
  docs/ctl/kmeshctl.md
  docs/ctl/kmeshctl_authz.md
  pkg/bpf/bpf.go
  pkg/bpf/workload/xdp.go
  pkg/constants/constants.go
  pkg/controller/controller.go
  pkg/status/status_server.go
Labels: lgtm, approved, size/XXL

#1054 fix bpf load failed in Ubuntu
  bpf/kmesh/workload/xdp.c
Labels: kind/bug, lgtm, approved, size/XS

#1056 Add kmesh ut test on 5.15
  .github/workflows/main-5.15.yml
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  hack/run-ut.sh
  hack/utils.sh
Labels: size/M

#1059 optimize: fix bpf ins over 100w
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/service.h
Labels: kind/bug, lgtm, approved, size/L

#1051 fix sockops prog load failed in Ubuntu kernel-enhanced env
  bpf/include/bpf_common.h
  bpf/kmesh/ads/include/ctx/sock_ops.h
Labels: kind/bug, lgtm, approved, size/S

#1060 Provides functions to get and update kmeshconfigMap.
  pkg/bpf/bpf.go
  pkg/bpf/bpf_test.go
  pkg/status/status_server.go
Labels: kind/enhancement, lgtm, approved, size/L

#1049 Optimize service lb policy update
  pkg/controller/workload/cache/endpoint_cache.go
  pkg/controller/workload/cache/endpoint_cache_test.go
  pkg/controller/workload/workload_processor.go
Labels: kind/enhancement, lgtm, approved, size/M

#1063 add E2E test for istio 1.24 to CI
  .github/workflows/e2e-ipv6-istio-1.24.yml
  .github/workflows/e2e-istio-1.24.yml
Labels: kind/enhancement, lgtm, approved, size/M

#1068 Changed log level for authz_offload=0 case
  bpf/kmesh/workload/xdp.c
Labels: lgtm, approved, size/XS

#1055 Improvement of metriclabels removal capability at workload granularity
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/utils.go
Labels: kind/enhancement, lgtm, approved, size/M

#1073 fix Flake of TestAddRemovePodWaypoint
  test/e2e/baseline_test.go
Labels: kind/bug, lgtm, approved, size/XS, cherrypick/release-0.5

#1067 Change enableAccesslog in the startup parameter to enableMetric
  bpf/include/common.h
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  bpf/kmesh/probes/probe.h
  ctl/accesslog/accesslog.go
  ctl/common/common.go
  ctl/monitoring/monitoring.go
  daemon/options/bpf.go
  docs/ctl/kmeshctl.md
  docs/ctl/kmeshctl_monitoring.md
  pkg/bpf/bpf.go
  pkg/constants/constants.go
  pkg/controller/client.go
  pkg/controller/controller.go
  pkg/controller/telemetry/metric.go
  pkg/controller/workload/workload_controller.go
  pkg/status/status_server.go
  pkg/status/status_server_test.go
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/XL

#1070 map_mertic and bpf_prog_metric test
  pkg/controller/telemetry/bpf_prog_metric_test.go
  pkg/controller/telemetry/map_metric_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1066 fix repeat string field proc
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  pkg/cache/v2/listener_test.go
Labels: kind/bug, lgtm, approved, size/L

#987 kernel-native mode support restart
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  pkg/bpf/ads/loader_enhanced.go
  pkg/bpf/ads/sock_connection.go
  pkg/bpf/ads/sock_ops.go
  pkg/bpf/ads/trace_point.go
  pkg/bpf/bpf.go
  pkg/bpf/bpf_test.go
  pkg/bpf/utils/bpf_helper.go
  pkg/bpf/workload/sendmsg.go
  pkg/bpf/workload/sock_connection.go
  pkg/bpf/workload/sock_ops.go
  pkg/cache/v2/cluster.go
  pkg/cache/v2/listener.go
  pkg/cache/v2/route.go
  pkg/constants/constants.go
  pkg/controller/ads/ads_processor.go
Labels: lgtm, approved, kind/feature, size/L, do-not-merge/contains-merge-commits

#1079 fix kmeshctl auth command description
  ctl/authz/authz.go
  docs/ctl/kmeshctl.md
  docs/ctl/kmeshctl_authz.md
Labels: lgtm, approved, size/S

#1047 Correct Workload handle order
  pkg/controller/workload/bpfcache/endpoint.go
  pkg/controller/workload/bpfcache/endpoint_test.go
  pkg/controller/workload/cache/endpoint_cache.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: lgtm, approved, size/L
