Repository kmesh-net/kmesh, pull requests merged in 2024-06, with the labels that each got.

#400 support identity rbac
  pkg/auth/rbac.go
Labels: lgtm, approved, size/S

#410 bpf: Dual-license the code as GPL-2.0 OR BSD-2-Clause
  .gitignore
  README.md
  bpf/COPYING
  bpf/LICENSE.BSD-2-Clause
  bpf/LICENSE.GPL-2.0
  bpf/deserialization_to_bpf_map/Makefile
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
  bpf/include/bpf_common.h
  bpf/include/bpf_helper_defs_ext.h
  bpf/include/bpf_log.h
  bpf/include/common.h
  bpf/include/errno.h
  bpf/kmesh/ads/cgroup_sock.c
  bpf/kmesh/ads/include/cluster.h
  bpf/kmesh/ads/include/config.h
  bpf/kmesh/ads/include/ctx/sock_addr.h
  bpf/kmesh/ads/include/ctx/sock_ops.h
  bpf/kmesh/ads/include/filter.h
  bpf/kmesh/ads/include/kmesh_common.h
  bpf/kmesh/ads/include/listener.h
  bpf/kmesh/ads/include/route_config.h
  bpf/kmesh/ads/include/tail_call.h
  bpf/kmesh/ads/include/tcp_proxy.h
  bpf/kmesh/ads/sockops.c
  bpf/kmesh/ads/tracepoint.c
  bpf/kmesh/bpf2go/bpf2go.go
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/config.h
  bpf/kmesh/workload/include/ctx/sock_addr.h
  bpf/kmesh/workload/include/encoder.h
  bpf/kmesh/workload/include/endpoint.h
  bpf/kmesh/workload/include/frontend.h
  bpf/kmesh/workload/include/service.h
  bpf/kmesh/workload/include/tail_call.h
  bpf/kmesh/workload/include/workload.h
  bpf/kmesh/workload/include/workload_common.h
  bpf/kmesh/workload/sendmsg.c
  bpf/kmesh/workload/sockops.c
  bpf/kmesh/workload/xdp.c
  oncn-mda/CMakeLists.txt
  oncn-mda/cli_src/CMakeLists.txt
  oncn-mda/cli_src/func/chain.c
  oncn-mda/cli_src/func/global.c
  oncn-mda/cli_src/func/log.c
  oncn-mda/cli_src/func/query.c
  oncn-mda/cli_src/func/switch.c
  oncn-mda/cli_src/mdacore.c
  oncn-mda/ebpf_src/CMakeLists.txt
  oncn-mda/ebpf_src/sock_ops.c
  oncn-mda/ebpf_src/sock_redirect.c
  oncn-mda/include/data.h
  oncn-mda/include/log.h
  oncn-mda/include/macli.h
  oncn-mda/include/mesh_accelerate.h
Labels: lgtm, approved, size/XXL

#392 Dump workload
  pkg/cache/v2/route.go
  pkg/controller/ads/ads_processor.go
  pkg/controller/client.go
  pkg/controller/client_test.go
  pkg/controller/controller.go
  pkg/controller/workload/cache/workload_cache.go
  pkg/status/status_server.go
Labels: lgtm, approved, size/L

#390 Make use of FIFQ instead of priority queue
  pkg/controller/controller.go
  pkg/controller/security/caclient.go
  pkg/controller/security/manager.go
Labels: lgtm, approved, size/L

#412 update make clean
  Makefile
Labels: lgtm, approved, size/XS

#411 use peer_metadata to get pod metadata info from istiod
  deploy/helm/templates/l7-envoyfilter.yaml
  deploy/yaml/l7-envoyfilter.yaml
Labels: kind/enhancement, lgtm, approved, size/M

#413 Support service dump
  api/v2/workloadapi/workload_helper.go
  daemon/manager/manager.go
  pkg/controller/workload/cache/service_cache.go
  pkg/controller/workload/workload_processor.go
  pkg/status/api.go
  pkg/status/status_server.go
  pkg/status/status_server_test.go
  pkg/status/testdata/workload_configdump.json
Labels: lgtm, approved, size/XL

#422 Fix bug when delete waypoint, dont update bpf kmesh_service map
  bpf/kmesh/workload/include/endpoint.h
  bpf/kmesh/workload/include/service.h
  pkg/controller/workload/workload_processor.go
Labels: kind/bug, lgtm, approved, size/L

#416 Improve security manager
  daemon/manager/manager.go
  daemon/options/options.go
  daemon/options/secret_manager.go
  pkg/controller/controller.go
  pkg/controller/security/caclient.go
  pkg/controller/security/manager.go
  pkg/controller/security/option.go
  pkg/controller/workload/workload_processor.go
Labels: kind/enhancement, lgtm, approved, size/L

#426 add make test for run ut easily
  Makefile
  hack/run-ut.sh
Labels: kind/enhancement, lgtm, approved, size/S

#419 Added dataplane mode constants
  pkg/cni/plugin/plugin.go
  pkg/constants/constants.go
Labels: lgtm, approved, size/S

#337 add proposal of Kmesh observability
  docs/proposal/observability.md
  docs/proposal/pics/observability.svg
Labels: lgtm, approved, size/L

#429 Subscribe cached resources when delta xds reconnect
  pkg/controller/workload/workload_controller.go
  pkg/controller/workload/workload_processor.go
Labels: lgtm, approved, size/M

#425 Added workload response handler tests
  pkg/controller/ads/ads_controller_test.go
  pkg/controller/client_test.go
  pkg/controller/workload/bpfcache/fake_map.go
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
  pkg/controller/xdstest/fake_xdsclient.go
  pkg/controller/xdstest/fake_xdsserver.go
  pkg/nets/nets.go
Labels: lgtm, approved, size/L

#434 Ipv6 Support - IPv6 compatibility refactor
  .clang-format
  bpf/include/bpf_common.h
  bpf/include/common.h
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/ctx/sock_addr.h
  bpf/kmesh/workload/include/encoder.h
  bpf/kmesh/workload/include/endpoint.h
  bpf/kmesh/workload/include/frontend.h
  bpf/kmesh/workload/include/service.h
  bpf/kmesh/workload/include/workload.h
  bpf/kmesh/workload/sendmsg.c
  bpf/kmesh/workload/sockops.c
  bpf/kmesh/workload/xdp.c
  pkg/auth/rbac.go
  pkg/bpf/bpf_kmesh_workload.go
  pkg/controller/workload/bpfcache/backend.go
  pkg/controller/workload/bpfcache/frontend.go
  pkg/controller/workload/bpfcache/service.go
  pkg/controller/workload/cache/workload_cache.go
  pkg/controller/workload/cache/workload_cache_test.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
  pkg/nets/nets.go
  pkg/utils/test/bpf_map.go
Labels: lgtm, approved, kind/feature, do-not-merge/contains-merge-commits, size/XL

#433 Provides a solution for running ut with docker and a solution for running locally
  Makefile
  hack/run-ut.sh
  hack/utils.sh
  kmesh_compile.sh
Labels: kind/enhancement, lgtm, approved, size/L

#441 fix error link in readme
  README.md
Labels: lgtm, approved, size/XS

#432 Mount proc
  deploy/helm/templates/daemonset.yaml
  deploy/yaml/kmesh.yaml
  pkg/controller/bypass/bypass_controller.go
Labels: lgtm, approved, size/S

#439 fix typos of dns resolver proposal
  docs/proposal/dns_resolve.md
Labels: lgtm, approved, size/S

#435 Fix authPolicy remove
  api/v2/workloadapi/security/authorization_help.go
  pkg/auth/policy_store.go
  pkg/auth/policy_store_test.go
  pkg/auth/rbac.go
  pkg/auth/rbac_test.go
  pkg/controller/workload/cache/workload_cache.go
Labels: lgtm, approved, size/XXL

#442 add kmesh-daemon dump command
  daemon/manager/dump/dump.go
  daemon/manager/manager.go
  daemon/manager/version/version.go
  pkg/status/status_server.go
Labels: lgtm, approved, size/M

#445 Bump istio
  cniplugin/main.go
  common/config/.golangci.yaml
  go.mod
  go.sum
  pkg/nets/connect.go
Labels: lgtm, approved, size/L

#444 Update dependabot.yml
  .github/dependabot.yml
Labels: lgtm, approved, size/XS

#431 Enable go race detect
  .github/workflows/main.yml
  .gitignore
  hack/run-ut.sh
Labels: lgtm, approved, size/S

#402 Kmesh eBPF log user space dumping
  bpf/include/bpf_log.h
  bpf/include/common.h
  bpf/kmesh/ads/cgroup_sock.c
  bpf/kmesh/ads/include/cluster.h
  bpf/kmesh/ads/include/filter.h
  bpf/kmesh/ads/include/listener.h
  bpf/kmesh/ads/include/route_config.h
  bpf/kmesh/ads/sockops.c
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/frontend.h
  bpf/kmesh/workload/include/service.h
  bpf/kmesh/workload/xdp.c
  config/kmesh_marcos_def.h
  daemon/manager/manager.go
  daemon/options/bpf.go
  deploy/helm/values.yaml
  kmesh_macros_env.sh
  pkg/bpf/bpf_kmesh.go
  pkg/constants/constants.go
  pkg/controller/controller.go
  pkg/logger/logger.go
  pkg/status/status_server.go
Labels: kind/enhancement, lgtm, approved, kind/feature, size/L

#446 Support dynamic changing log level in status manager
  pkg/logger/logger.go
  pkg/status/status_server.go
  pkg/status/status_server_test.go
Labels: lgtm, approved, kind/feature, size/L, do-not-merge/contains-merge-commits

#438 Bug fix on xds handler
  pkg/cache/v2/cluster.go
  pkg/cache/v2/maps/cluster.go
  pkg/controller/ads/ads_controller.go
  pkg/controller/ads/ads_processor.go
  pkg/controller/ads/ads_processor_test.go
Labels: kind/bug, lgtm, approved, size/L

#456 bug fix
  .clang-format
  bpf/include/bpf_common.h
  bpf/include/common.h
  bpf/kmesh/workload/sendmsg.c
Labels: kind/bug, lgtm, approved, size/M

#407 Simplify byteorder transformation & remove magic number in Authz
  pkg/auth/rbac.go
  pkg/auth/rbac_test.go
  pkg/auth/xdp_auth_handler.go
  pkg/controller/client.go
Labels: kind/enhancement, lgtm, approved, size/L

#461 fix compile failed on openEuler 2203
  bpf/include/common.h
Labels: kind/bug, lgtm, approved, size/XS

#454 Refactor clusterCache flush and Fix EDS ACK
  api/core/base.proto
  api/v2-c/core/base.pb-c.c
  api/v2-c/core/base.pb-c.h
  api/v2/core/base.pb.go
  pkg/controller/ads/ads_processor.go
  pkg/controller/ads/ads_processor_test.go
Labels: kind/bug, lgtm, approved, size/L

#459 Add log sub command for kmesh-daemon
  daemon/manager/log/log.go
  daemon/manager/manager.go
  pkg/logger/logger.go
  pkg/status/status_server.go
  pkg/status/status_server_test.go
Labels: lgtm, approved, size/L

#443 E2E test framework
  .github/workflows/main.yml
  Makefile
  deploy/helm/templates/daemonset.yaml
  deploy/yaml/kmesh.yaml
  docs/proposal/e2e.md
  docs/proposal/pics/e2e-arch.png
  go.mod
  go.sum
  test/e2e/baseline_test.go
  test/e2e/main_test.go
  test/e2e/run_test.sh
Labels: lgtm, approved, kind/feature, size/XXL

#393 add security manager test
  pkg/controller/security/caclient.go
  pkg/controller/security/caclient_test.go
  pkg/controller/security/manager.go
  pkg/controller/security/manager_test.go
  pkg/controller/security/mock/mockcaclient.go
  pkg/controller/security/testdata/ca-cert.pem
  pkg/controller/security/testdata/ca-key.pem
  pkg/controller/security/testdata/cert-chain.pem
  pkg/controller/security/testdata/key.pem
  pkg/controller/security/testdata/root-cert.pem
Labels: lgtm, approved, kind/feature, size/XL

#464 Should send initial authz resources when reconnect
  pkg/auth/policy_store.go
  pkg/auth/rbac.go
  pkg/controller/ads/ads_processor.go
  pkg/controller/client.go
  pkg/controller/workload/workload_controller.go
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: lgtm, approved, size/L
