Repository kmesh-net/kmesh, pull requests merged in 2024-10, with the labels that each got.

#932 infra(ci): update copyright check ci
  .github/workflows/main.yml
  Makefile
  cniplugin/main.go
  config/kmesh_marcos_def.h
  daemon/main.go
  daemon/manager/manager.go
  daemon/manager/version/version.go
  daemon/options/bpf.go
  daemon/options/bypass.go
  daemon/options/cni.go
  daemon/options/options.go
  daemon/options/secret_manager.go
  depends/include/bpf_helper_defs_ext.h
  hack/copyright-check.sh
  hack/copyright/copyright_scan_dir.json
  hack/gen-check.sh
  kernel/ko_src/kmesh/defer_connect.c
  kernel/ko_src/kmesh/defer_connect.h
  kernel/ko_src/kmesh/kmesh_main.c
  kernel/ko_src/kmesh/kmesh_parse_http_1_1.c
  kernel/ko_src/kmesh/kmesh_parse_http_1_1.h
  kernel/ko_src/kmesh/kmesh_parse_protocol_data.c
  kernel/ko_src/kmesh/kmesh_parse_protocol_data.h
  pkg/utils/kernel_version.go
  test/e2e/restart_test.go
Labels: lgtm, approved, size/L

#711 Fix argument list too long in manage controller
  pkg/controller/manage/manage_controller.go
  pkg/utils/enroll.go
  pkg/utils/enroll_test.go
Labels: lgtm, approved, kind/cleanup, size/L

#929 upgrade golang to 1.23
  .github/workflows/e2e-ipv6-istio-1.23.yml
  .github/workflows/e2e-ipv6.yml
  .github/workflows/e2e-istio-1.23.yml
  .github/workflows/e2e.yml
  .github/workflows/main.yml
  build/docker/builder.dockerfile
  go.mod
Labels: kind/enhancement, lgtm, approved, size/S

#934 Add maintainers file
  MAINTAINERS.md
Labels: lgtm, approved, size/S

#935 enable/disable accesslog with kmeshctl
  ctl/accesslog/accesslog.go
  ctl/dump/dump.go
  ctl/log/log.go
  ctl/main.go
  ctl/utils/utils.go
  ctl/version/version.go
  pkg/controller/telemetry/metric.go
  pkg/controller/workload/workload_controller.go
  pkg/status/status_server.go
  pkg/status/status_server_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#940 change `ads`->`kernel-native` and `workload`->`duel-engine` in code
  ctl/dump/dump.go
  daemon/options/bpf.go
  deploy/charts/kmesh-helm/values.yaml
  deploy/yaml/kmesh.yaml
  pkg/auth/policy_store_test.go
  pkg/auth/rbac_test.go
  pkg/bpf/bpf.go
  pkg/bpf/bpf_test.go
  pkg/cache/v2/cluster_test.go
  pkg/cache/v2/listener_test.go
  pkg/cache/v2/route_test.go
  pkg/cni/chained_test.go
  pkg/cni/install.go
  pkg/cni/install_test.go
  pkg/cni/plugin/plugin.go
  pkg/constants/constants.go
  pkg/controller/ads/ads_processor.go
  pkg/controller/ads/ads_processor_test.go
  pkg/controller/client.go
  pkg/controller/client_test.go
  pkg/controller/config/config.go
  pkg/controller/controller.go
  pkg/controller/manage/manage_controller.go
  pkg/controller/manage/manage_controller_test.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
  pkg/logger/logger.go
  pkg/status/status_server_test.go
Labels: lgtm, approved, size/L

#942 fix format error of `kmeshctl waypoint status --help`
  ctl/waypoint/waypoint.go
Labels: kind/bug, lgtm, approved, size/XS

#916 rm depends/include/bpf_helper_defs_ext.h
  Makefile
  depends/include/bpf_helper_defs_ext.h
  hack/format.sh
  kmesh_bpf_env.sh
Labels: lgtm, approved, size/S

#948 Fix github action arm image built
  .github/workflows/release-master.yaml
  build/docker/github.dockerfile
Labels: lgtm, approved, size/M

#957 Ignore key not exist error when delete bpf map
  pkg/controller/workload/bpfcache/auth_policy.go
  pkg/controller/workload/bpfcache/backend.go
  pkg/controller/workload/bpfcache/endpoint.go
  pkg/controller/workload/bpfcache/frontend.go
  pkg/controller/workload/bpfcache/service.go
  pkg/controller/workload/workload_processor.go
Labels: kind/enhancement, lgtm, approved, size/M

#960 if sourceworkload is nil, not print metrics
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
Labels: lgtm, approved, size/S

#958 check whether pods should be managed when ns is managed
  pkg/controller/manage/manage_controller.go
  pkg/controller/manage/manage_controller_test.go
  pkg/utils/enroll.go
Labels: kind/bug, lgtm, approved, size/L

#950 Bump istio dependencies
  ctl/waypoint/waypoint.go
  go.mod
  go.sum
  pkg/controller/client.go
  pkg/controller/manage/manage_controller.go
  pkg/controller/security/manager.go
  pkg/dns/dns.go
  test/e2e/baseline_test.go
  test/e2e/main_test.go
  test/e2e/manage_test.go
Labels: lgtm, approved, size/XL

#974 install istioctl in tmp dir when running E2E tests
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/S

#976 Fix MAINTAINERS file misspelling
  MAINTAINERS.md
Labels: lgtm, approved, size/XS

#906 E2E Enhancement Draft
  test/e2e/baseline_test.go
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/M

#982 add clusterid in grpc stream context
  pkg/controller/client.go
Labels: kind/bug, lgtm, approved, size/XS

#980 g_inner_map_mng.inner_map support persist in restart
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
Labels: kind/enhancement, lgtm, approved, size/M

#986 Fix the typo
  test/e2e/run_test.sh
Labels: kind/bug, lgtm, approved, size/XS

#983 update readme.md.
  README.md
  docs/pics/dual-engine-mode.png
  docs/pics/kernel-native-mode.png
Labels: lgtm, approved, size/S

#989 Static compile cni and ctl
  Makefile
Labels: lgtm, approved, size/S

#900 Add locality loadbalance to kmesh workload mode.
  bpf/kmesh/workload/include/service.h
  bpf/kmesh/workload/include/workload.h
  bpf/kmesh/workload/include/workload_common.h
  pkg/controller/workload/bpfcache/endpoint.go
  pkg/controller/workload/bpfcache/locality_cache.go
  pkg/controller/workload/bpfcache/locality_cache_test.go
  pkg/controller/workload/bpfcache/service.go
  pkg/controller/workload/cache/endpoint_cache.go
  pkg/controller/workload/cache/endpoint_cache_test.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
  pkg/status/status_server_test.go
Labels: kind/enhancement, lgtm, approved, size/XL, ok-to-test

#570 maintain cluster active connection counter for circuit breaker
  api/cluster/cluster.proto
  api/v2-c/cluster/cluster.pb-c.c
  api/v2-c/cluster/cluster.pb-c.h
  api/v2/cluster/cluster.pb.go
  bpf/kmesh/ads/include/circuit_breaker.h
  bpf/kmesh/ads/include/cluster.h
  bpf/kmesh/ads/include/config.h
  bpf/kmesh/ads/include/ctx/sock_addr.h
  bpf/kmesh/ads/include/ctx/sock_ops.h
  bpf/kmesh/ads/include/kmesh_common.h
  bpf/kmesh/ads/sockops.c
  daemon/manager/manager.go
  kernel/ko_src/kmesh/defer_connect.c
  pkg/bpf/ads/loader.go
  pkg/bpf/ads/loader_enhanced.go
  pkg/bpf/bpf.go
  pkg/bpf/workload/sock_connection.go
  pkg/bpf/workload/sock_ops.go
  pkg/bpf/workload/xdp.go
  pkg/cache/v2/cluster.go
  pkg/cache/v2/cluster_test.go
  pkg/controller/ads/ads_controller.go
  pkg/controller/ads/ads_controller_test.go
  pkg/controller/ads/ads_processor.go
  pkg/controller/ads/ads_processor_test.go
  pkg/controller/ads/cache.go
  pkg/controller/ads/cache_test.go
  pkg/controller/client.go
  pkg/controller/client_test.go
  pkg/controller/controller.go
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
  pkg/dns/dns_test.go
  pkg/utils/hash_name.go
  pkg/utils/hash_name_test.go
  samples/circuitbreaker/circuitbreaker.yml
Labels: lgtm, approved, size/XL, ok-to-test

#973 fix cannot get RDS after grpc reconnect
  pkg/controller/ads/ads_processor.go
  pkg/controller/ads/ads_processor_test.go
Labels: kind/bug, lgtm, approved, size/S, cherrypick/release-0.5

#920 add xdp test
  docs/pics/xdp_test_result1.png
  docs/pics/xdp_test_result2.png
  docs/unit_test_doc.md
  test/unittest/workload/Makefile
  test/unittest/workload/common.h
  test/unittest/workload/run_tests.sh
  test/unittest/workload/xdp_test.c
Labels: lgtm, approved, size/XL

#397 Add proposal for circuit breaker
  docs/proposal/circuit_breaker.md
  docs/proposal/pics/circuit_breaker_example.png
  docs/proposal/pics/kmesh_ads_mode_sockops_flow.png
  docs/proposal/pics/kmesh_circuit_breaker_flow.png
  docs/proposal/pics/outlier_detection.png
Labels: lgtm, approved, size/L

#778 add unit_test_framework proposal
  docs/proposal/pics/unit_test_flow.png
  docs/proposal/unit_test_framework_zh.md
Labels: lgtm, approved, size/XL

#887 Add Performance Monitoring
  bpf/kmesh/probes/performance_probe.h
  bpf/kmesh/probes/probe.h
  bpf/kmesh/workload/cgroup_sock.c
  daemon/options/options.go
  daemon/options/perf.go
  deploy/yaml/kmesh.yaml
  docs/proposal/performance_monitoring.md
  docs/proposal/pics/kmesh_daemon_monitoring.jpg
  docs/proposal/pics/kmesh_map_and_operation_monitoring.jpg
  docs/proposal/pics/performance_monitoring.jpg
  pkg/controller/controller.go
  pkg/controller/telemetry/map_metric.go
  pkg/controller/telemetry/operation_metric.go
  pkg/controller/telemetry/utils.go
  pkg/controller/workload/workload_controller.go
  samples/addons/grafana.yaml
  samples/addons/kmesh_performance-monitoring.json
  samples/addons/prometheus.yaml
Labels: lgtm, approved, kind/feature, size/XXL

#859 ads: support envoy filter local ratelimit.
  api/filter/ratelimit.proto
  api/listener/listener_components.proto
  api/v2-c/filter/ratelimit.pb-c.c
  api/v2-c/filter/ratelimit.pb-c.h
  api/v2-c/listener/listener_components.pb-c.c
  api/v2-c/listener/listener_components.pb-c.h
  api/v2/filter/ratelimit.pb.go
  api/v2/listener/listener_components.pb.go
  bpf/kmesh/ads/include/filter.h
  bpf/kmesh/ads/include/local_ratelimit.h
  go.mod
  pkg/controller/ads/cache.go
  pkg/controller/ads/extensions/local_ratelimit.go
  pkg/controller/ads/extensions/local_ratelimit_test.go
Labels: approved, size/XXL
