Repository kmesh-net/kmesh, pull requests merged in 2024-01, with the labels that each got.

#70 docs:image build and usage
  README-zh.md
  README.md
  build/docker/README.md
  build/docker/kmesh.yaml
  docs/kmesh_compile-zh.md
  docs/kmesh_compile.md
Labels: lgtm, approved, size/L

#82 update oncn.io to kmesh.net
  api/Makefile
  api/admin/config_dump.proto
  api/cluster/circuit_breaker.proto
  api/cluster/cluster.proto
  api/core/address.proto
  api/core/base.proto
  api/endpoint/endpoint.proto
  api/filter/http_connection_manager.proto
  api/filter/tcp_proxy.proto
  api/listener/listener.proto
  api/listener/listener_components.proto
  api/route/route.proto
  api/route/route_components.proto
  cmd/command/config.go
  cmd/command/http_server.go
  cmd/main.go
  cniplugin/main.go
  daemon/main.go
  daemon/manager/manager.go
  go.mod
  pkg/bpf/bpf.go
  pkg/bpf/bpf_kmesh.go
  pkg/bpf/bpf_kmesh_common.go
  pkg/bpf/config.go
  pkg/cache/v2/cluster.go
  pkg/cache/v2/flush.go
  pkg/cache/v2/listener.go
  pkg/cache/v2/maps/cluster.go
  pkg/cache/v2/maps/common.go
  pkg/cache/v2/maps/listener.go
  pkg/cache/v2/maps/route.go
  pkg/cache/v2/route.go
  pkg/cni_plg/chained.go
  pkg/cni_plg/cni_plg.go
  pkg/cni_plg/config.go
  pkg/cni_plg/plugin/plugin.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/envoy/ads_client.go
  pkg/controller/envoy/ads_config.go
  pkg/controller/envoy/ads_event.go
  pkg/controller/envoy/ads_loader.go
  pkg/controller/envoy/convert_filter.go
  pkg/nets/config.go
  pkg/utils/exec.go
Labels: lgtm, approved, size/L

#84 add issus template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/good-first.md
  .github/ISSUE_TEMPLATE/question.md
Labels: lgtm, approved, size/M

#51 Kmesh: add docs for multiple dataplane
  docs/multiple dataplane_CN.md
  docs/multiple dataplane_EN.md
  docs/pics/client_with_envoy.png
  docs/pics/client_with_envoy_server_with_envoy.png
  docs/pics/client_with_noenvoy.png
  docs/pics/client_with_noenvoy_server_with_envoy.png
  docs/pics/multiple_dataplane_design.png
Labels: lgtm, approved

#87 Add gitignore
  .gitignore
Labels: lgtm, approved, size/M

#89 optimize README to make quickstart easy
  README-zh.md
  README.md
Labels: lgtm, approved, size/M

#90 add a pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, size/S

#92 Add Github Action workflow for CI
  .github/workflows/main.yml
  build.sh
  kmesh_compile_env_pre.sh
Labels: kind/enhancement, lgtm, approved, size/M

#97 fix golang lint
  .github/workflows/main.yml
  cmd/command/http_client.go
  cmd/command/http_server.go
  common/config/.golangci.yaml
  daemon/main.go
  daemon/manager/manager.go
  mk/bpf.pc
  pkg/cni_plg/cni_plg.go
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/envoy/ads_client.go
  pkg/controller/envoy/ads_config.go
  pkg/controller/envoy/ads_event.go
  pkg/controller/envoy/ads_loader.go
  pkg/controller/envoy/convert_filter.go
  pkg/controller/interfaces/client.go
  pkg/logger/logger.go
  pkg/nets/connect.go
  pkg/options/options.go
  pkg/utils/exec.go
Labels: lgtm, approved, size/L

#88 Install kmesh-cni from kmesh daemon
  .gitignore
  Makefile
  build/docker/README.md
  build/docker/clusterrole.yaml
  build/docker/clusterrolebinding
  build/docker/kmesh.yaml
  build/docker/serviceaccount.yaml
  build/docker/start_kmesh.sh
  cniplugin/main.go
  docs/multiple dataplane_CN.md
  docs/multiple dataplane_EN.md
  kmesh.spec
  pkg/cni_plg/chained.go
  pkg/cni_plg/kubeconfig.go
  pkg/cni_plg/plugin/plugin.go
  pkg/controller/envoy/ads_config.go
  pkg/utils/fileop.go
  pkg/utils/kubeclient.go
Labels: lgtm, approved, size/L

#100 Fix CI workflow and fix golint issues
  .github/workflows/main.yml
  common/config/.golangci.yaml
  pkg/bpf/bpf.go
  pkg/bpf/bpf_kmesh_common.go
  pkg/bpf/bpf_kmesh_l4.go
  pkg/bpf/pin.go
  pkg/cache/v2/maps/cluster.go
  pkg/cache/v2/maps/common.go
  pkg/cache/v2/maps/listener.go
  pkg/cache/v2/maps/route.go
  pkg/cni_plg/kubeconfig.go
Labels: kind/bug, lgtm, approved, size/L

#99 Donot intercept traffic from sidecar
  cniplugin/main.go
  daemon/manager/manager.go
  pkg/cni/chained.go
  pkg/cni/config.go
  pkg/cni/install.go
  pkg/cni/kubeconfig.go
  pkg/cni/plugin/plugin.go
Labels: kind/enhancement, lgtm, approved, size/L
