Repository kmesh-net/kmesh, pull requests merged in 2024-04, with the labels that each got.

#188 Make use of cobra command
  daemon/main.go
  daemon/manager/manager.go
  deploy/helm/values.yaml
  deploy/yaml/kmesh.yaml
  docs/kmesh_commands-zh.md
  docs/kmesh_commands.md
  go.mod
  pkg/bpf/config.go
  pkg/cni/config.go
  pkg/controller/config/config.go
  pkg/controller/dump/dump_ads.go
  pkg/controller/envoy/ads_loader.go
  pkg/nets/config.go
  pkg/options/options.go
  pkg/pid/pid_file.go
  test/testcases/kmesh/libs/common.sh
Labels: lgtm, approved, size/L

#200 Fixed incorrect function usage when deleting routes
  pkg/cache/v2/cluster.go
  pkg/cache/v2/route.go
Labels: lgtm, approved, size/S

#197 add ut of cache/v2/cluster.go
  pkg/cache/v2/cluster_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#180 add ut of ads_event.go
  pkg/controller/envoy/ads_event_test.go
Labels: kind/enhancement, lgtm, approved, size/XL

#194 add ut of cache/v2/listener.go
  pkg/cache/v2/listener_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#192 add ut of cache/v2/route.go
  pkg/cache/v2/route_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#205 Improved robustness of UT tests
  pkg/cache/v2/cluster_test.go
Labels: lgtm, approved, size/XS

#207 Improving the robustness of listener ut
  pkg/cache/v2/listener_test.go
Labels: kind/enhancement, lgtm, approved, size/XS

#202 add ut of workload_cache.go
  pkg/controller/workload/workload_cache_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#212 fix go test env variable invalidation
  .github/workflows/main.yml
Labels: lgtm, approved, size/XS

#216 replace rotatelogs to lumberjack
  go.mod
  go.sum
  pkg/logger/logger.go
Labels: kind/enhancement, lgtm, approved, size/M

#206 fix no responseNonce in AdsRequest
  pkg/controller/envoy/ads_event.go
  pkg/controller/envoy/ads_event_test.go
  pkg/controller/envoy/ads_stream.go
Labels: kind/bug, lgtm, approved, size/L

#218 update golang.org/x/net to fix a vulnerability
  go.mod
  go.sum
Labels: kind/enhancement, lgtm, approved, size/XS

#223 Kmesh auth: fix npe
  pkg/bpf/bpf_kmesh_workload.go
Labels: kind/bug, lgtm, approved, size/XS

#219 fix kmesh.ko location
  build/docker/start_kmesh.sh
Labels: lgtm, approved, size/XS

#222 Fix image name error in kmesh.yaml
  deploy/yaml/kmesh.yaml
Labels: lgtm, approved, size/XS

#224 support l7 routing in kmesh
  README-zh.md
  README.md
  deploy/helm/templates/l7-envoyfilter.yaml
  deploy/yaml/l7-envoyfilter.yaml
Labels: lgtm, approved, size/L

#195 Fix POD_NAME env
  Makefile
  build/docker/README.md
  deploy/helm/templates/daemonset.yaml
  deploy/helm/values.yaml
  deploy/yaml/kmesh.yaml
  pkg/controller/config/config.go
  pkg/controller/config/config_test.go
Labels: lgtm, approved, size/L

#208 Added an example to test bpf map in ut
  pkg/bpf/bpf_kmesh_common.go
  pkg/controller/envoy/ads_event_test.go
Labels: lgtm, approved, size/M

#226 update gitignore
  .gitignore
Labels: lgtm, approved, size/XS

#220 store waypoint data to bakcend map and no service pod ip to forntend map
  bpf/kmesh/workload/include/workload.h
  pkg/controller/workload/workload_backend.go
  pkg/controller/workload/workload_event.go
  pkg/controller/workload/workload_frontend.go
Labels: lgtm, approved, size/L

#228 Kmesh auth: fix prog name too long
  bpf/kmesh/workload/sockops_tuple.c
  bpf/kmesh/workload/xdp.c
  pkg/bpf/bpf_kmesh_workload.go
  pkg/cni/plugin/plugin.go
Labels: kind/bug, lgtm, approved, size/S

#179 Kmesh: Introduce a new method to query whether a pod is managed by Kmesh
  bpf/kmesh/workload/include/config.h
  bpf/kmesh/workload/sockops_tuple.c
  pkg/cni/plugin/plugin.go
  pkg/cni/plugin/plugin_test.go
Labels: lgtm, approved, size/L

#233 Kmesh auth: enable rbac only when Kmesh starts in workload mode
  pkg/auth/rbac.go
  pkg/bpf/config.go
  pkg/controller/client.go
Labels: kind/enhancement, lgtm, approved, size/S

#232 Optimised UT with test bpf map in ut
  pkg/controller/envoy/ads_event_test.go
  pkg/controller/envoy/ads_stream_test.go
Labels: kind/enhancement, lgtm, approved, size/M

#227 Kmesh: Add waypoint support for connect and deliver encoder dst info to sendmsg ebpf
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/tail_call.h
  bpf/kmesh/workload/sockops_tuple.c
  pkg/bpf/bpf_kmesh_workload.go
Labels: lgtm, approved, size/L

#235 Kmesh auth: add OWNERS in pkg/auth
  pkg/auth/OWNERS
Labels: kind/enhancement, lgtm, approved, size/XS

#236 Enable workload mode by default
  daemon/manager/manager.go
  deploy/helm/values.yaml
  deploy/yaml/kmesh.yaml
  pkg/bpf/bpf.go
  pkg/bpf/config.go
  pkg/cni/config.go
  pkg/cni/install.go
  pkg/controller/client.go
  pkg/controller/config/config.go
  pkg/controller/controller.go
Labels: lgtm, approved, size/M

#237 Revert "fix kmesh_compile image version"
  Makefile
  docs/kmesh_compile-zh.md
  docs/kmesh_compile.md
  kmesh_compile.sh
Labels: lgtm, approved, size/M

#238 fix kmesh_compile image version
  kmesh_compile.sh
Labels: lgtm, approved, size/XS

#243 Kmesh: optimize log level
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/endpoint.h
  bpf/kmesh/workload/include/frontend.h
  bpf/kmesh/workload/include/service.h
Labels: lgtm, approved, size/S

#245 Optimization: check and mount the bpf file system during kmesh startup
  build/docker/start_kmesh.sh
Labels: lgtm, approved, size/XS

#242 Kmesh: Introduce a new method record pod control by Kmesh
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/config.h
  bpf/kmesh/workload/include/workload.h
  bpf/kmesh/workload/sockops_tuple.c
  pkg/cni/plugin/plugin.go
  pkg/cni/plugin/plugin_test.go
Labels: lgtm, approved, size/L

#248 Kmesh: Add the deleted annotation information to the pod
  pkg/cni/plugin/plugin.go
Labels: lgtm, approved, size/S

#241 update gitignore because bpf2go update
  .gitignore
Labels: lgtm, approved, size/XS

#251 add bypass code
  build/docker/kmesh.dockerfile
  deploy/helm/templates/daemonset.yaml
  deploy/helm/templates/kmesh-rbac.yaml
  deploy/yaml/clusterrole.yaml
  deploy/yaml/kmesh.yaml
  go.mod
  go.sum
  pkg/controller/bypass/bypass_controller.go
  pkg/controller/controller.go
Labels: lgtm, approved, kind/feature, size/XL

#249 fix cluster mismatch in envoyfilters and add arch suffix for waypoint image
  README-zh.md
  README.md
  deploy/helm/templates/l7-envoyfilter.yaml
  deploy/yaml/l7-envoyfilter.yaml
Labels: kind/bug, lgtm, approved, size/S

#254 Kmesh: disable kmesh for waypoint pod
  pkg/cni/plugin/plugin.go
Labels: lgtm, approved, size/XS

#255 store target port with KmeshWaypointPort for waypoint scene
  pkg/controller/workload/workload_event.go
Labels: lgtm, approved, size/S

#252 Kmesh: adapt ads ebpf program for cni
  bpf/kmesh/cgroup_sock.c
  bpf/kmesh/include/config.h
Labels: lgtm, approved, size/M

#258 fix kmesh manager pod restart failed in ads mode
  pkg/cni/plugin/plugin.go
Labels: lgtm, approved, size/XS

#262 Delete unnecessary code and configuration
  deploy/helm/templates/daemonset.yaml
  deploy/yaml/kmesh.yaml
Labels: lgtm, approved, size/XS

#263 Fix dns typed service panic
  pkg/controller/envoy/ads_loader.go
  pkg/nets/nets.go
  pkg/nets/nets_test.go
Labels: lgtm, approved, size/M

#260 Enable xdp auth when kmesh works in workload mode
  pkg/bpf/bpf_kmesh_workload.go
  pkg/bpf/config.go
  pkg/cni/chained.go
  pkg/cni/chained_test.go
  pkg/cni/install.go
  pkg/cni/plugin/plugin.go
  pkg/constants/constants.go
Labels: kind/enhancement, lgtm, approved, size/L

#231 Enable dependa bot
  .github/dependabot.yml
Labels: lgtm, approved, size/S

#259 Added benchmark test for cluster.Flush()
  pkg/cache/v2/cluster_test.go
Labels: lgtm, approved, size/L

#253 Added benchmark test for listener.Flush()
  pkg/cache/v2/listener_test.go
  pkg/controller/envoy/ads_event_test.go
  pkg/utils/test/bpf_map.go
Labels: lgtm, approved, size/L

#272 fix authz on server listening on both ipv4 and ipv6 port
  bpf/kmesh/workload/sockops_tuple.c
Labels: lgtm, approved, size/S

#267 opt cluster ut test
  pkg/cache/v2/cluster_test.go
Labels: lgtm, approved, size/M

#276 add yaml of sample applications
  samples/httpbin/httpbin.yaml
  samples/sleep/sleep.yaml
Labels: lgtm, approved, size/M

#278 rename service_id to upstream_id in frontend_value struct
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/frontend.h
  bpf/kmesh/workload/include/workload.h
  pkg/controller/workload/workload_event.go
  pkg/controller/workload/workload_frontend.go
Labels: lgtm, approved, size/S

#213 add ut of client.go
  pkg/controller/client_test.go
Labels: lgtm, approved, size/L

#266 add clang-format
  .clang-format
  Makefile
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
  bpf/include/bpf_log.h
  bpf/include/common.h
  bpf/include/errno.h
  bpf/kmesh/cgroup_sock.c
  bpf/kmesh/include/cluster.h
  bpf/kmesh/include/config.h
  bpf/kmesh/include/ctx/sock_addr.h
  bpf/kmesh/include/ctx/sock_ops.h
  bpf/kmesh/include/filter.h
  bpf/kmesh/include/kmesh_common.h
  bpf/kmesh/include/listener.h
  bpf/kmesh/include/route_config.h
  bpf/kmesh/include/tail_call.h
  bpf/kmesh/include/tcp_proxy.h
  bpf/kmesh/sockops.c
  bpf/kmesh/tracepoint.c
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/config.h
  bpf/kmesh/workload/include/ctx/sock_addr.h
  bpf/kmesh/workload/include/endpoint.h
  bpf/kmesh/workload/include/frontend.h
  bpf/kmesh/workload/include/service.h
  bpf/kmesh/workload/include/workload.h
  bpf/kmesh/workload/include/workload_common.h
  bpf/kmesh/workload/sendmsg.c
  bpf/kmesh/workload/sockops_tuple.c
  bpf/kmesh/workload/xdp.c
  config/kmesh_marcos_def.h
  depends/include/bpf_helper_defs_ext.h
  hack/format.sh
  kernel/ko_src/kmesh/defer_connect.c
  kernel/ko_src/kmesh/defer_connect.h
  kernel/ko_src/kmesh/kmesh_main.c
  kernel/ko_src/kmesh/kmesh_parse_http_1_1.c
  kernel/ko_src/kmesh/kmesh_parse_http_1_1.h
  kernel/ko_src/kmesh/kmesh_parse_protocol_data.c
  kernel/ko_src/kmesh/kmesh_parse_protocol_data.h
  oncn-mda/cli_src/func/chain.c
  oncn-mda/cli_src/func/global.c
  oncn-mda/cli_src/func/log.c
  oncn-mda/cli_src/func/query.c
  oncn-mda/cli_src/func/switch.c
  oncn-mda/cli_src/mdacore.c
  oncn-mda/ebpf_src/sock_ops.c
  oncn-mda/ebpf_src/sock_redirect.c
  oncn-mda/include/data.h
  oncn-mda/include/log.h
  oncn-mda/include/macli.h
  oncn-mda/include/mesh_accelerate.h
Labels: lgtm, approved, size/XXL

#284 bump istio to fix proto conflict
  go.mod
  go.sum
  pkg/controller/client_test.go
  pkg/controller/config/config.go
  pkg/controller/envoy/ads_stream_test.go
  pkg/controller/xdstest/fake_xdsserver.go
Labels: lgtm, approved, size/L
