Repository kmesh-net/kmesh, pull requests merged in 2024-07, with the labels that each got.

#473 bug fix
  bpf/include/bpf_common.h
Labels: kind/bug, lgtm, approved, size/XS

#472 Split E2E test as a separate CI jobs
  .github/workflows/e2e.yml
  .github/workflows/main.yml
Labels: kind/enhancement, lgtm, approved, size/S

#481 fix display error of e2e flags
  docs/proposal/e2e.md
Labels: lgtm, approved, size/XS

#468 optimization: normalized ADDR type
  bpf/kmesh/workload/sendmsg.c
Labels: lgtm, approved, kind/feature, size/XS

#430 add UT for bypass
  pkg/controller/bypass/bypass_controller.go
  pkg/controller/bypass/bypass_test.go
Labels: lgtm, approved, size/L

#485 Fix authz goroutine not started
  pkg/controller/client.go
  pkg/controller/controller.go
  pkg/controller/workload/workload_controller.go
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/workload/workload_processor.go
Labels: kind/bug, lgtm, approved, size/M

#482 fix hash name bug (#479)
  go.mod
  pkg/controller/workload/workload_hash.go
  pkg/controller/workload/workload_hash_test.go
Labels: lgtm, approved, size/L

#436 Support dns resolution typed service
  go.mod
  pkg/cache/v2/cluster.go
  pkg/cache/v2/route.go
  pkg/controller/ads/ads_processor.go
  pkg/controller/ads/ads_processor_test.go
  pkg/controller/ads/cache.go
  pkg/controller/client_test.go
  pkg/controller/controller.go
  pkg/dns/dns.go
  pkg/dns/dns_test.go
Labels: lgtm, approved, kind/feature, size/XL

#483 Fix bpfloglevel update error bug in Ads mode.
  daemon/manager/manager.go
  pkg/bpf/bpf.go
  pkg/bpf/bpf_kmesh_l4_workload.go
  pkg/status/status_server.go
Labels: kind/bug, lgtm, approved, size/S

#491 support run specified unit test (#488)
  hack/run-ut.sh
Labels: lgtm, approved, size/S

#500 merge log handlers (#498)
  pkg/constants/constants.go
  pkg/status/status_server.go
Labels: lgtm, approved, size/M

#499 fix flaky e2e test
  test/e2e/baseline_test.go
  test/e2e/run_test.sh
Labels: kind/bug, lgtm, approved, size/M

#513 keep the same as helm deploy
  deploy/yaml/kmesh.yaml
Labels: lgtm, approved, size/XS

#502 Add Okabe-Rintarou-0 to pkg/status owners
  pkg/status/OWNERS
Labels: lgtm, approved, size/XS

#493 update issue label
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: lgtm, approved, size/XS

#516 fix workloadController.run() not called error
  pkg/controller/controller.go
Labels: lgtm, approved, size/XS

#515 Add some uts for setting bpf log level
  hack/run-ut.sh
  pkg/status/status_server_test.go
Labels: lgtm, approved, size/M

#506 cleanup stopch(#497)
  daemon/manager/manager.go
  pkg/controller/bypass/bypass_controller.go
  pkg/controller/bypass/bypass_test.go
  pkg/controller/controller.go
  pkg/controller/manage/kmesh_manage.go
  pkg/controller/manage/kmesh_manage_test.go
Labels: kind/enhancement, lgtm, approved, size/M

#508 modify oncn-mda to be compatible with kernel 6.6
  build/docker/kmesh.dockerfile
  hack/utils.sh
  kmesh.spec
  oncn-mda/cli_src/func/global.c
  oncn-mda/cli_src/func/switch.c
  oncn-mda/ebpf_src/sock_ops.c
  oncn-mda/include/data.h
  oncn-mda/include/macli.h
  oncn-mda/include/mesh_accelerate.h
Labels: lgtm, approved, size/L

#517 adjust bpf map size for large-scale cluster
  bpf/include/bpf_common.h
  bpf/kmesh/workload/include/config.h
  bpf/kmesh/workload/include/encoder.h
  bpf/kmesh/workload/include/workload.h
Labels: kind/enhancement, lgtm, approved, size/S

#518 Add compilation macro for oncn-mda
  oncn-mda/cli_src/func/global.c
  oncn-mda/cli_src/func/switch.c
  oncn-mda/include/macli.h
Labels: lgtm, approved, size/M

#519 Add missing copy right
  bpf/kmesh/bpf2go/bpf2go.go
  test/e2e/baseline_test.go
  test/e2e/main_test.go
Labels: lgtm, approved, size/M

#466 eBPF observability
  bpf/include/bpf_common.h
  bpf/include/bpf_log.h
  bpf/kmesh/bpf2go/bpf2go.go
  bpf/kmesh/probes/access_log.h
  bpf/kmesh/probes/metrics.h
  bpf/kmesh/probes/probe.h
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/sockops.c
  docs/proposal/ebpf-observability.md
  docs/proposal/pics/probe.svg
Labels: lgtm, approved, kind/feature, size/L, do-not-merge/contains-merge-commits

#526 Support ns manage after kmesh restart
  pkg/constants/constants.go
  pkg/controller/manage/kmesh_manage.go
Labels: lgtm, approved, size/M

#530 waypoint listen both ipv4 and ipv6
  deploy/helm/templates/l7-envoyfilter.yaml
  deploy/yaml/l7-envoyfilter.yaml
Labels: kind/enhancement, lgtm, approved, size/S

#531 kmesh route samples
  samples/fortio/fortio-header.yaml
  samples/fortio/fortio-route.yaml
  samples/fortio/fortio-v1-10-v2-90.yaml
  samples/fortio/netuils.yaml
Labels: lgtm, approved, size/L

#527 Kmesh Observability
  bpf/kmesh/probes/metrics.h
  go.mod
  pkg/constants/constants.go
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
  pkg/controller/telemetry/utils.go
  pkg/controller/telemetry/utils_test.go
  pkg/controller/workload/workload_controller.go
Labels: kind/enhancement, lgtm, approved, kind/feature, size/XXL

#533 [cherry-pick 0.4] Kmesh observability
  bpf/kmesh/probes/metrics.h
  go.mod
  pkg/constants/constants.go
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
  pkg/controller/telemetry/utils.go
  pkg/controller/telemetry/utils_test.go
  pkg/controller/workload/workload_controller.go
Labels: lgtm, approved

#535 fix unexpected log
  pkg/controller/workload/workload_hash.go
Labels: lgtm, approved, size/XS

#540 Fix TestPodSidecarLabelChangeTriggersAddIptablesAction flake
  pkg/controller/bypass/bypass_controller.go
  pkg/controller/bypass/bypass_test.go
Labels: lgtm, approved, size/S

#541 Modifybpf map update to prevent potential bugs
  bpf/include/bpf_common.h
  bpf/kmesh/workload/sockops.c
Labels: lgtm, approved, size/XS

#544 modify kmesh version to v0.4.0
  Makefile
Labels: lgtm, approved, kind/feature, size/XS

#537 add codecov config
  .codecov.yml
  .github/workflows/main.yml
Labels: lgtm, approved, size/S

#554 use latest waypoint image to run e2e
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/XS

#559 add document for deploying and developing in kind
  docs/kmesh_deploy_and_develop_in_kind.md
Labels: lgtm, approved, size/L

#564 add security.md for kmesh
  SECURITY.md
Labels: lgtm, approved, size/XS

#562 Add bpf log level getter (#560)
  daemon/manager/log/log.go
  pkg/status/status_server.go
  pkg/status/status_server_test.go
Labels: lgtm, approved, size/L

#565 add document about using enhanced kernel
  docs/kmesh_deploy_and_develop_in_kind.md
  docs/kmesh_use_enhanced_kernel.md
  docs/pics/install_openEuler.png
Labels: lgtm, approved, size/M

#572 update gitignore for enhanced kernel
  .gitignore
Labels: lgtm, approved, size/S

#573 Add code spell check github workflow
  .codespellrc
  .github/ISSUE_TEMPLATE/membership-request.md
  .github/workflows/code-spell.yml
  CONTRIBUTING.md
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/kmesh/ads/include/cluster.h
  bpf/kmesh/ads/include/listener.h
  bpf/kmesh/probes/metrics.h
  bpf/kmesh/probes/probe.h
  bpf/kmesh/workload/include/service.h
  bpf/kmesh/workload/sockops.c
  build.sh
  daemon/options/cni.go
  deploy/yaml/kmesh.yaml
  docs/kmesh_commands-zh.md
  docs/kmesh_commands.md
  docs/proposal/dns_resolve.md
  docs/proposal/e2e.md
  docs/proposal/ebpf-observability.md
  docs/proposal/kmesh_support_workload.md
  docs/proposal/tls_cert_zh.md
  kernel/ko_src/kmesh/kmesh_parse_http_1_1.c
  oncn-mda/cli_src/func/switch.c
  oncn-mda/ebpf_src/sock_ops.c
  pkg/auth/rbac.go
  pkg/bpf/pin.go
  pkg/controller/ads/ads_processor.go
  pkg/controller/ads/cache.go
  pkg/controller/ads/cache_test.go
  pkg/controller/bypass/bypass_controller.go
  pkg/controller/client_test.go
  pkg/controller/telemetry/metric.go
  pkg/controller/workload/workload_processor.go
  pkg/logger/logger.go
  pkg/utils/nettools.go
Labels: lgtm, approved, size/L

#576 add badge in readme
  README.md
Labels: lgtm, approved, size/XS

#557 Provide a way to allow setting all logger level to debug
  bpf/include/bpf_log.h
  bpf/kmesh/ads/include/kmesh_common.h
  bpf/kmesh/workload/include/workload_common.h
Labels: lgtm, approved, size/M

#582 Fix `make gen` problem
  api/Makefile
  api/v2-c/admin/config_dump.pb-c.h
  api/v2-c/cluster/circuit_breaker.pb-c.h
  api/v2-c/cluster/cluster.pb-c.h
  api/v2-c/core/address.pb-c.h
  api/v2-c/core/base.pb-c.h
  api/v2-c/endpoint/endpoint.pb-c.h
  api/v2-c/filter/http_connection_manager.pb-c.h
  api/v2-c/filter/tcp_proxy.pb-c.h
  api/v2-c/listener/listener.pb-c.h
  api/v2-c/listener/listener_components.pb-c.h
  api/v2-c/route/route.pb-c.h
  api/v2-c/route/route_components.pb-c.h
  api/v2-c/workloadapi/security/authorization.pb-c.h
  api/v2-c/workloadapi/workload.pb-c.h
  hack/gen_protoc.sh
  hack/install-proto.sh
Labels: lgtm, approved, size/L

#587 fix make clean
  Makefile
Labels: lgtm, approved, size/XS

#580 add some waypoint related E2E test cases
  test/e2e/README.md
  test/e2e/baseline_test.go
  test/e2e/main_test.go
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/L

#590 optimize workload update
  pkg/controller/workload/workload_processor.go
Labels: kind/enhancement, lgtm, approved, size/XS

#585 remove arch info in build process
  Makefile
  build/docker/kmesh.dockerfile
  hack/utils.sh
Labels: lgtm, approved, size/M

#489 kmesh security: pod manage
  pkg/constants/constants.go
  pkg/controller/controller.go
  pkg/controller/manage/kmesh_manage.go
  pkg/controller/manage/kmesh_manage_test.go
  pkg/controller/security/manager.go
  pkg/controller/workload/workload_processor.go
Labels: kind/enhancement, lgtm, approved, size/L

#589 add configuration to collect kmesh metrics using Prometheus
  deploy/helm/templates/daemonset.yaml
  deploy/yaml/kmesh.yaml
  samples/addons/prometheus.yaml
  samples/tcp-echo/tcp-echo-ipv4.yaml
  samples/tcp-echo/tcp-echo-ipv6.yaml
  samples/tcp-echo/tcp-echo.yaml
Labels: kind/enhancement, lgtm, approved, size/XL

#598 fix pod management can not be canceled
  pkg/controller/manage/kmesh_manage.go
Labels: lgtm, approved, size/XS

#611 waypoint should not managed by Kmesh
  pkg/controller/manage/kmesh_manage.go
  pkg/controller/manage/kmesh_manage_test.go
Labels: kind/bug, lgtm, approved, size/L

#601 remove resync period
  pkg/controller/bypass/bypass_controller.go
  pkg/controller/manage/kmesh_manage.go
Labels: lgtm, approved, size/S

#604 Fix DNS cluster's endpoint ip addr check
  pkg/dns/dns.go
  pkg/dns/dns_test.go
Labels: lgtm, approved, size/L, cherrypick/release-0.4

#615 [release 0.4.0]waypoint should not managed by Kmesh
  pkg/controller/manage/kmesh_manage.go
  pkg/controller/manage/kmesh_manage_test.go
Labels: kind/bug, lgtm, approved, size/L

#622 remove build arch in documents
  docs/kmesh_compile-zh.md
  docs/kmesh_compile.md
  docs/kmesh_deploy_and_develop_in_kind.md
Labels: lgtm, approved, size/XS

#607 Bypass only for sidecar
  pkg/controller/bypass/bypass_controller.go
  pkg/controller/bypass/bypass_test.go
  pkg/controller/controller.go
  pkg/controller/manage/manage_controller.go
  pkg/controller/manage/manage_controller_test.go
Labels: lgtm, approved, size/L

#627 update metric_key with direction & dst_port
  bpf/kmesh/probes/metrics.h
Labels: kind/enhancement, lgtm, approved, size/M

#625 E2E test cases for waypoint management
  .codespellrc
  test/e2e/baseline_test.go
  test/e2e/main_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#623 Make kmesh cni and manage controller consitent during pod enrollment
  pkg/cni/plugin/plugin.go
  pkg/cni/plugin/plugin_test.go
  pkg/constants/constants.go
  pkg/controller/bypass/bypass_controller.go
  pkg/controller/manage/manage_controller.go
  pkg/controller/manage/manage_controller_test.go
  pkg/utils/enroll.go
  pkg/utils/enroll_test.go
  pkg/utils/istio/sidecar.go
  pkg/utils/istio/sidecar_test.go
Labels: kind/enhancement, lgtm, approved, size/XXL

#475 kmesh support restart by reload old bpf map and prog
  build/docker/start_kmesh.sh
  daemon/manager/manager.go
  deploy/helm/templates/kmesh-rbac.yaml
  deploy/yaml/clusterrole.yaml
  pkg/bpf/bpf.go
  pkg/bpf/bpf_kmesh_workload.go
  pkg/bpf/bpf_restart.go
  pkg/bpf/bpf_restart_test.go
  pkg/constants/constants.go
  pkg/utils/test/bpf_map.go
Labels: lgtm, approved, kind/feature, size/L

#638 enable select some e2e cases to run or skip some cases
  docs/proposal/e2e.md
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/S

#633 copy bytes optimize
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
  pkg/nets/nets.go
  pkg/nets/nets_test.go
Labels: lgtm, approved, size/M

#634 preclude pod with host network to be managed by kmesh
  pkg/utils/enroll.go
  pkg/utils/enroll_test.go
Labels: kind/enhancement, lgtm, approved, size/M

#635 remove bypass from bpf prog
  bpf/include/bpf_common.h
  bpf/kmesh/ads/cgroup_sock.c
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/sockops.c
Labels: lgtm, approved, kind/cleanup, size/L

#649 Enable cleanup in e2e
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/S

#651 Fix kmesh daemon graceful exit
  build/docker/start_kmesh.sh
  pkg/bpf/bpf_restart.go
  pkg/status/status_server.go
Labels: lgtm, approved, size/S, cherrypick/release-0.4

#636 Fix TestPodSidecarLabelChangeTriggersAddIptablesAction flake
  pkg/controller/bypass/bypass_controller.go
  pkg/controller/bypass/bypass_test.go
Labels: kind/bug, lgtm, approved, size/M
