Repository kmesh-net/kmesh, pull requests merged in 2024-12, with the labels that each got.

#1075 Remove enable-bpf-log from the startup parameters
  daemon/options/bpf.go
  deploy/charts/kmesh-helm/values.yaml
  deploy/yaml/kmesh.yaml
  pkg/controller/controller.go
Labels: lgtm, approved, kind/cleanup, size/S

#1085 add configuration to collect the Prometheus metrics from Kmesh and rename them into a format that Kiali can read.
  samples/addons/prometheus_recording_istio.yaml
Labels: lgtm, approved, size/XL

#1086 remove spammy log from authz
  bpf/kmesh/workload/sockops.c
  bpf/kmesh/workload/xdp.c
Labels: lgtm, approved, size/XS

#1080 add support for PROTOBUF_C_TYPE_BYTES
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/include/bpf_common.h
  bpf/include/common.h
  bpf/include/inner_map_defs.h
Labels: lgtm, approved, size/M

#1084 add prefix km_ in almost all kmesh bpf map
  Makefile
  bpf/include/bpf_common.h
  bpf/include/bpf_log.h
  bpf/include/common.h
  bpf/include/map_config.h
  bpf/kmesh/ads/include/config.h
  bpf/kmesh/ads/include/local_ratelimit.h
  bpf/kmesh/ads/include/route_config.h
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  bpf/kmesh/probes/performance_probe.h
  bpf/kmesh/workload/include/authz.h
  bpf/kmesh/workload/include/config.h
  bpf/kmesh/workload/include/tail_call.h
  bpf/kmesh/workload/sockops.c
  pkg/bpf/ads/loader.go
  pkg/bpf/ads/sock_connection.go
  pkg/bpf/workload/loader.go
  pkg/bpf/workload/sock_connection.go
  pkg/bpf/workload/sock_ops.go
  pkg/bpf/workload/xdp.go
  pkg/consistenthash/maglev/maglev.go
  pkg/controller/controller.go
  pkg/controller/workload/bpfcache/auth_policy.go
  pkg/controller/workload/bpfcache/backend.go
  pkg/controller/workload/bpfcache/endpoint.go
  pkg/controller/workload/bpfcache/fake_map.go
  pkg/controller/workload/bpfcache/frontend.go
  pkg/controller/workload/bpfcache/service.go
  pkg/controller/workload/workload_controller.go
  pkg/logger/logger.go
  pkg/status/status_server_test.go
Labels: lgtm, approved, size/XXL

#1087 Refact: Bpf log reader start
  bpf/include/bpf_log.h
  bpf/include/map_config.h
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  pkg/controller/controller.go
  pkg/logger/logger.go
Labels: lgtm, approved, size/L

#1096 delete unnecessary kmeshctl handlers
  pkg/status/status_server.go
Labels: lgtm, approved, kind/cleanup, size/S

#1097 update mapname in kernelnative enhanced
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfel.go
  pkg/bpf/ads/loader_enhanced.go
  pkg/bpf/ads/sock_ops.go
Labels: lgtm, approved, size/XL

#1101 Add kiali addon sample and adjust prometheus_recording_istio sample
  samples/addons/kiali.yaml
  samples/addons/prometheus_recording_istio.yaml
Labels: kind/enhancement, lgtm, approved, size/L

#1093 Support workload granularity metrics dynamicly turn on with kmeshctl
  ctl/monitoring/monitoring.go
  docs/ctl/kmeshctl_monitoring.md
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
  pkg/controller/workload/workload_controller.go
  pkg/status/status_server.go
Labels: kind/enhancement, lgtm, approved, size/L

#1102 Optimised handling when no podCIDR is available
  pkg/bpf/bpf.go
Labels: kind/bug, lgtm, approved, size/XS

#1077 Skip matching svc again in backend_manager
  bpf/kmesh/workload/include/backend.h
Labels: lgtm, approved, size/S

#1109 update issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/question.md
Labels: kind/enhancement, lgtm, approved, size/XS

#1103 Expand the ringbuf size of tcp_info
  bpf/kmesh/probes/tcp_probe.h
Labels: kind/enhancement, lgtm, approved, size/XS

#1107 update kmesh_support.md
  docs/kmesh_support.md
Labels: documentation, lgtm, approved, size/M

#574 add proposal for Locality LoadBalance
  docs/proposal/kmesh_support_localityLB.md
  docs/proposal/pics/locality_lb.svg
Labels: kind/enhancement, lgtm, approved, size/XXL, ok-to-test

#1114 Add kmesh-daemon version subcommand and fix `kmeshctl version`
  Makefile
  ctl/version/version.go
  daemon/manager/manager.go
  daemon/manager/version/version.go
  docs/ctl/kmeshctl_version.md
  pkg/kube/portforwarder.go
Labels: lgtm, approved, size/L

#1094 update hostname and record unknown services of service metrics
  pkg/controller/ads/cache.go
  pkg/controller/telemetry/accesslog.go
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
  pkg/controller/workload/cache/waypoint_cache.go
  pkg/controller/workload/cache/waypoint_cache_test.go
  pkg/controller/workload/workload_controller.go
  pkg/controller/workload/workload_processor.go
  test/e2e/baseline_test.go
Labels: kind/bug, lgtm, approved, size/XL

#1098 combining repeating fucntion of UT together for workload
  pkg/controller/workload/cache/waypoint_cache_test.go
  pkg/controller/workload/cache/workload_cache_test.go
  pkg/controller/workload/common/fake_helpers.go
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/workload/workload_processor_test.go
Labels: lgtm, approved, size/L, do-not-merge/contains-merge-commits

#1115 fix start failed in enhanced kernel-native mode
  bpf/kmesh/ads/include/config.h
  bpf/kmesh/ads/include/ctx/sock_addr.h
  bpf/kmesh/ads/include/ctx/sock_ops.h
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  pkg/bpf/ads/sock_connection.go
  pkg/bpf/ads/sock_ops.go
  pkg/bpf/utils/pin.go
Labels: kind/bug, lgtm, approved, size/L

#1122 Clean dead code in xdp loader
  pkg/bpf/utils/pin.go
  pkg/bpf/workload/xdp.go
Labels: lgtm, approved, size/XS

#1106 better bpf logging
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/endpoint.h
  bpf/kmesh/workload/include/frontend.h
  bpf/kmesh/workload/include/service.h
Labels: lgtm, approved, size/M

#1124 Bump istio and k8s dependencies
  go.mod
  go.sum
  pkg/controller/ads/convert_filter_test.go
  pkg/controller/config/config_test.go
  pkg/controller/security/manager.go
  pkg/dns/dns.go
Labels: lgtm, approved, size/XL

#1136 fix Invalid size: -1
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
Labels: kind/bug, lgtm, approved, size/XS

#1108 add E2E test "TestServiceEntrySelectsWorkloadEntry"
  test/e2e/baseline_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1123 rename bpf map names to be more explicit
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/probes/tcp_probe.h
  bpf/kmesh/workload/include/authz.h
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/config.h
  bpf/kmesh/workload/include/encoder.h
  bpf/kmesh/workload/include/tail_call.h
  bpf/kmesh/workload/include/workload.h
  bpf/kmesh/workload/sendmsg.c
  bpf/kmesh/workload/sockops.c
  bpf/kmesh/workload/xdp.c
  docs/proposal/layer4_authorization.md
  pkg/auth/rbac.go
  pkg/auth/rbac_test.go
  pkg/auth/xdp_auth_handler.go
  pkg/bpf/workload/loader.go
  pkg/bpf/workload/sock_connection.go
  pkg/bpf/workload/xdp.go
  pkg/constants/constants.go
  pkg/controller/workload/workload_controller.go
  test/unittest/workload/xdp_test.c
Labels: lgtm, approved, size/XXL

#1121 misc bug fix in manage controller
  pkg/controller/manage/manage_controller.go
Labels: lgtm, approved, kind/cleanup, size/L

#1133 Optimised kmeshConfigMap to avoid initialising it every time kmesh reboot.
  pkg/bpf/bpf.go
Labels: kind/enhancement, lgtm, approved, size/M

#1127 remove spammy log cause by unknown service access
  bpf/kmesh/workload/cgroup_sock.c
Labels: lgtm, approved, size/S

#1143 fix service DEBUG log report negative number
  bpf/kmesh/workload/include/backend.h
Labels: kind/bug, lgtm, approved, size/XS

#1142 Fix after kmesh daemon restart, xdp should be re linked
  pkg/controller/manage/manage_controller.go
Labels: lgtm, approved, size/S

#1135 refine destination service metrics generation
  bpf/include/errno.h
  bpf/kmesh/probes/tcp_probe.h
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/frontend.h
  bpf/kmesh/workload/sendmsg.c
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
  pkg/controller/workload/cache/service_cache.go
Labels: lgtm, approved, size/XL

#1148 Optimise the update logic of the frontend table to cope with duplicate service and workload addresses.
  api/v2/workloadapi/workload_helper.go
  pkg/controller/workload/workload_processor.go
  pkg/nets/nets.go
  pkg/nets/nets_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1151 Modified log handling in workload_processor
  pkg/controller/workload/workload_processor.go
Labels: kind/enhancement, lgtm, approved, size/S

#1150 change TestCompareIpByte to table driven test
  pkg/nets/nets_test.go
Labels: lgtm, approved, size/M

#1095 support xdp auth of IPs
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  bpf/include/common.h
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/workload/include/authz.h
  bpf/kmesh/workload/include/tail_call.h
  bpf/kmesh/workload/include/workload_common.h
  bpf/kmesh/workload/xdp.c
  pkg/bpf/workload/xdp.go
  pkg/constants/constants.go
Labels: lgtm, approved, size/L

#1027 add proposal for xdp authz
  docs/proposal/layer4_authorization.md
  docs/proposal/pics/istio_policy_module.png
  docs/proposal/pics/kmesh_l4_authorization_match_chain.svg
  docs/proposal/pics/kmesh_l4_authorization_xdp.svg
  docs/proposal/pics/kmesh_xdp_authz.jpg
Labels: lgtm, approved, size/M
