Repository kmesh-net/kmesh, pull requests merged in 2024-03, with the labels that each got.

#142 Replaced kubernetes.ClientSet with kubernetes.Interface
  pkg/cni/plugin/plugin.go
  pkg/utils/kubeclient.go
Labels: kind/enhancement, lgtm, approved, size/S

#143 A ut of cni plugin
  .github/workflows/main.yml
  go.mod
  go.sum
  pkg/cni/plugin/plugin.go
  pkg/cni/plugin/plugin_test.go
  pkg/logger/logger.go
Labels: kind/enhancement, lgtm, approved, size/L

#145 add ut of cni_chain
  pkg/cni/chained_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#138 refactor controller code
  .gitignore
  Makefile
  build/docker/README.md
  build/docker/kmesh.dockerfile
  build/kmesh.service
  cmd/command/config.go
  cmd/command/http_client.go
  cmd/main.go
  daemon/manager/manager.go
  deploy/helm/values.yaml
  deploy/yaml/kmesh.yaml
  docs/kmesh_commands-zh.md
  docs/kmesh_commands.md
  docs/kmesh_compile-zh.md
  docs/kmesh_compile.md
  docs/kmesh_development_guide.md
  go.mod
  kmesh_compile.sh
  oncn-mda/README.md
  pkg/bpf/config.go
  pkg/controller/client.go
  pkg/controller/config.go
  pkg/controller/config/config.go
  pkg/controller/controller.go
  pkg/controller/dump/dump_ads.go
  pkg/controller/envoy/ads_client.go
  pkg/controller/envoy/ads_config.go
  pkg/controller/envoy/ads_event.go
  pkg/controller/envoy/ads_loader.go
  pkg/controller/envoy/ads_stream.go
  pkg/controller/envoy/convert_filter.go
  pkg/controller/interfaces/client.go
  pkg/controller/workload/workload_backend.go
  pkg/controller/workload/workload_endpoint.go
  pkg/controller/workload/workload_event.go
  pkg/controller/workload/workload_frontend.go
  pkg/controller/workload/workload_hash.go
  pkg/controller/workload/workload_service.go
  pkg/controller/workload/workload_stream.go
  pkg/controller_workload/config.go
  pkg/controller_workload/controller.go
  pkg/controller_workload/interfaces/client.go
  pkg/controller_workload/workload/workload_client.go
Labels: lgtm, approved, size/XXL

#141 Kmesh authorization
  api/v2-c/workloadapi/security/authorization.pb-c.c
  api/v2-c/workloadapi/security/authorization.pb-c.h
  api/v2/workloadapi/security/authorization.pb.go
  api/workloadapi/security/authorization.proto
  go.mod
  go.sum
  pkg/auth/policy_store.go
  pkg/auth/policy_store_test.go
  pkg/auth/rbac.go
  pkg/auth/rbac_test.go
  pkg/controller/workload/workload_event.go
  pkg/controller/workload/workload_stream.go
Labels: lgtm, approved, size/XXL

#149 update kmesh start script to exit when kmesh exit
  build/docker/start_kmesh.sh
Labels: kind/enhancement, lgtm, approved, size/S

#162 Modify the go version in the github CI to match the version in go.mod
  .github/workflows/main.yml
Labels: kind/enhancement, lgtm, approved, size/XS

#151 Added an issue template for requesting to be a member of the kmesh community
  .github/ISSUE_TEMPLATE/membership-request.md
Labels: kind/enhancement, lgtm, approved, size/M

#164 add ./out/amd64 in LD_LIBRARY_PATH
  .github/workflows/main.yml
Labels: lgtm, approved, size/XS

#156 set resource name when response for rds and eds type
  pkg/controller/envoy/ads_event.go
  pkg/controller/envoy/ads_loader.go
Labels: lgtm, approved, size/M

#166 Add reviwers for controller
  pkg/controller/OWNERS
Labels: lgtm, approved, size/S

#148 add bypass design
  docs/proposal/bypass.md
  docs/proposal/bypass_zh.md
  docs/proposal/pics/kmesh_bypass.svg
  docs/proposal/pics/kmesh_pre_bypass.svg
  docs/proposal/pics/kmesh_traffic_path.svg
  docs/proposal/pics/sidecar_bypass.svg
  docs/proposal/pics/sidecar_pre_bypass.svg
  docs/proposal/pics/sidecar_traffic_path.svg
Labels: lgtm, approved, size/L

#170 add nil pointer check in ads_loader.go
  pkg/controller/envoy/ads_loader.go
Labels: kind/bug, lgtm, approved, size/M

#152 Prevent writing empty cni conflist
  pkg/cni/chained.go
Labels: kind/bug, lgtm, approved, size/M

#174 fix start script
  build/docker/start_kmesh.sh
Labels: kind/bug, lgtm, approved, size/XS

#167 add /usr/lib64 in LD_LIBRARY_PATH
  .github/workflows/main.yml
Labels: lgtm, approved, size/XS

#177 set go test env
  .github/workflows/main.yml
Labels: lgtm, approved, size/XS

#175 Move the map of supported protocols out of ParseConfig() for easy querying.
  pkg/nets/config.go
Labels: kind/enhancement, lgtm, approved, size/S

#163 add ut of ads_stream.go
  go.mod
  go.sum
  pkg/controller/envoy/ads_stream_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#182 set resource name when response for rds and eds type
  pkg/controller/envoy/ads_event.go
  pkg/controller/envoy/ads_loader.go
Labels: lgtm, approved, size/M

#168 add ut of convert_filter_test.go
  go.mod
  go.sum
  pkg/controller/envoy/convert_filter_test.go
Labels: kind/enhancement, lgtm, approved, size/M

#187 Change `UpdateApiClusterStatus` in handleLdsResponse to `UpdateApiListenerStatus`
  pkg/controller/envoy/ads_event.go
Labels: kind/bug, lgtm, approved, size/XS

#160 Fix workload remove
  pkg/controller/workload/workload_event.go
Labels: lgtm, approved, size/M

#193 Supports portability of running images
  build/docker/kmesh.dockerfile
  build/docker/start_kmesh.sh
  kmesh_compile.sh
Labels: lgtm, approved, size/XS

#191 fix kmesh http parse header bug
  kernel/ko_src/kmesh/kmesh_parse_http_1_1.c
Labels: lgtm, approved, size/S

#161 add workload cache to be retrieved
  pkg/controller/workload/workload_cache.go
  pkg/controller/workload/workload_event.go
  pkg/nets/nets.go
Labels: lgtm, approved, size/L
