Repository kmesh-net/kmesh, pull requests merged in 2025-04, with the labels that each got.

#1290 remove deprecated flag `--enable-bpf-log` in e2e test
  test/e2e/run_test.sh
Labels: lgtm, approved, kind/cleanup, size/XS

#1247 Refactor dns
  pkg/controller/ads/ads_controller.go
  pkg/controller/ads/ads_controller_test.go
  pkg/controller/ads/dns.go
  pkg/controller/ads/dns_test.go
  pkg/controller/controller.go
  pkg/dns/dns.go
  pkg/dns/dns_test.go
  pkg/dns/utils.go
Labels: kind/enhancement, lgtm, approved, size/XXL

#1267 eBPF unit test: add proposal
  docs/proposal/ebpf_unit_test.md
  docs/proposal/ebpf_unit_test_zh.md
  docs/proposal/unit_test_framework_zh.md
Labels: kind/enhancement, lgtm, approved, size/XXL

#1302 update ubuntu 2404
  .github/workflows/e2e-ipv6-istio-1.23.yml
  .github/workflows/e2e-ipv6-istio-1.24.yml
  .github/workflows/e2e-ipv6.yml
Labels: lgtm, approved, size/XS

#1297 add e2e tests for isito 1.25 and remove e2e tests for isito 1.22
  .github/workflows/e2e-ipv6-istio-1.25.yml
  .github/workflows/e2e-istio-1.25.yml
Labels: kind/enhancement, lgtm, approved, size/XS

#1303 store original dst info in map_of_sock_storage and remove map_of_orig_dst
  bpf/include/bpf_common.h
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockops_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockops_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockopscompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockopscompat_bpfel.go
  bpf/kmesh/probes/tcp_probe.h
  bpf/kmesh/workload/cgroup_sock.c
  bpf/kmesh/workload/include/backend.h
  bpf/kmesh/workload/include/config.h
  bpf/kmesh/workload/include/encoder.h
  bpf/kmesh/workload/sendmsg.c
  bpf/kmesh/workload/sockops.c
Labels: kind/bug, lgtm, approved, size/XL

#1298 Tcp long conn metrics and accesslogs (new)
  bpf/include/bpf_common.h
  bpf/kmesh/bpf2go/bpf2go.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockops_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockops_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockopscompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockopscompat_bpfel.go
  bpf/kmesh/probes/performance_probe.h
  bpf/kmesh/probes/probe.h
  bpf/kmesh/probes/tcp_probe.h
  bpf/kmesh/workload/cgroup_skb.c
  bpf/kmesh/workload/sockops.c
  docs/proposal/pics/tcp_long_conn_design.png
  docs/proposal/tcp_long_connection_metrics.md
  pkg/bpf/workload/loader.go
  pkg/bpf/workload/skb.go
  pkg/controller/telemetry/accesslog.go
  pkg/controller/telemetry/accesslog_test.go
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
Labels: lgtm, approved, kind/feature, size/XXL

#1299 Add ebpf ut framework & Add xdp ut
  .github/workflows/main-5.15.yml
  .github/workflows/main.yml
  Makefile
  bpf/kmesh/workload/include/authz.h
  go.mod
  hack/run-ebpf-ut.sh
  kmesh_compile_env_pre.sh
  pkg/bpf/workload/loader.go
  pkg/constants/constants.go
  test/bpf_ut/.gitignore
  test/bpf_ut/Makefile
  test/bpf_ut/bpftest/bpf_test.go
  test/bpf_ut/bpftest/trf.pb.go
  test/bpf_ut/bpftest/trf.proto
  test/bpf_ut/bpftest/workload_test.go
  test/bpf_ut/include/ut_common.h
  test/bpf_ut/include/xdp_common.h
  test/bpf_ut/xdp_authz_offload_test.c
  test/bpf_ut/xdp_shutdown_in_userspace_test.c
Labels: kind/enhancement, lgtm, approved, size/XXL

#1306 fix build error：fatal error: 'encoder.h' file not found
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
  bpf/kmesh/workload/cgroup_skb.c
Labels: kind/bug, lgtm, approved, size/M

#1312 Skip test on 5.15 temporarily because ubuntu20.04 runner is removed
  .github/workflows/main-5.15.yml
Labels: lgtm, approved, size/M

#1314 fix kmesh daemon commands description
  docs/kmesh_commands-zh.md
  docs/kmesh_commands.md
Labels: documentation, lgtm, approved, size/M

#1324 rfac: added gomft in makefile
  CONTRIBUTING.md
  hack/format.sh
Labels: kind/enhancement, lgtm, approved, size/XS

#1320 Fix dead link
  CONTRIBUTING.md
Labels: lgtm, approved, size/XS

#1332 fix enhanced issue
  bpf/include/bpf_helper_defs_ext.h
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfel.go
  kmesh_bpf_env.sh
  pkg/bpf/ads/loader.go
  pkg/bpf/ads/loader_enhanced.go
Labels: kind/bug, lgtm, approved, size/XL

#1335 rfac: added config.h include in tcp_probe.h and cgroup_skb.h
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfel.go
  bpf/kmesh/probes/tcp_probe.h
  bpf/kmesh/workload/cgroup_skb.c
  bpf/kmesh/workload/sockops.c
Labels: kind/bug, lgtm, approved, size/S

#1347 Fix kmesh manage, especially after kmesh restart, old xdp prog maybe …
  pkg/controller/manage/manage_controller.go
Labels: kind/bug, lgtm, approved, size/M

#1345 fix workload processer panic if newWorkload addresses is nil when add serviceEntry
  pkg/controller/workload/workload_processor.go
Labels: kind/bug, lgtm, approved, size/XS

#1349 e2e test for l4 authorization
  test/e2e/baseline_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1353 Revert "e2e test for l4 authorization"
  test/e2e/baseline_test.go
Labels: lgtm, approved

#1342 fix: values is not updated in tcp_conn map #1341
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
  test/e2e/baseline_test.go
Labels: kind/bug, lgtm, approved, size/L

#1350 Fix cgroup_skb/* get sk_storage failed
  bpf/include/bpf_common.h
  bpf/kmesh/probes/probe.h
  bpf/kmesh/workload/cgroup_skb.c
Labels: kind/bug, lgtm, approved, size/M
