Repository kmesh-net/kmesh, pull requests merged in 2025-08, with the labels that each got.

#1446 Chore: bump github.com/spf13/pflag & lint fix
  docs/ebpf_unit_test_zh.md
  docs/multiple_dataplane_CN.md
  docs/multiple_dataplane_EN.md
  go.mod
  go.sum
  hack/format.sh
Labels: lgtm, approved, kind/cleanup, size/XS

#1445 Tune gemini review severity threshold to HIGH
  .gemini/config.yaml
Labels: kind/enhancement, lgtm, approved, size/S

#1461 add ipsec controller unit test
  pkg/controller/encryption/ipsec/ipsec_controller.go
  pkg/controller/encryption/ipsec/ipsec_controller_test.go
Labels: kind/enhancement, lgtm, approved, kind/security, size/XL

#1433 add(proposal): Added proposal for Kmesh website automation
  docs/pics/Chinese_doc_check.png
  docs/pics/kmeshctl-sync-1.png
  docs/pics/kmeshctl-sync-2.png
  docs/pics/website-versioning-archiving-1.png
  docs/pics/website-versioning-archiving-2.png
  docs/proposal/Kmesh_website_automation.md
Labels: lgtm, approved, size/L

#1473 fix file non-existent error when kmesh start with --enable-ipsec=true
  deploy/charts/kmesh-helm/templates/daemonset.yaml
  pkg/controller/encryption/ipsec/ipsec_controller.go
  pkg/controller/encryption/ipsec/ipsec_handler.go
Labels: kind/bug, kind/enhancement, lgtm, approved, size/S

#1478 Organize documentation by language
  docs/cn/zh/ebpf_unit_test_zh.md
  docs/cn/zh/kmesh_commands-zh.md
  docs/cn/zh/kmesh_compile-zh.md
  docs/cn/zh/kmesh_demo-zh.md
  docs/cn/zh/kmesh_development_guide.md
  docs/cn/zh/kmesh_kernel_compile-zh.md
  docs/cn/zh/kmesh_support-zh.md
  docs/cn/zh/multiple_dataplane_CN.md
  docs/cn/zh/xds_handle_zh.md
  docs/en/Startup_process_of_eBPF_programs.md
  docs/en/kmesh_commands.md
  docs/en/kmesh_compile.md
  docs/en/kmesh_demo.md
  docs/en/kmesh_deploy_and_develop_in_kind.md
  docs/en/kmesh_kernel_compile.md
  docs/en/kmesh_performance.md
  docs/en/kmesh_support.md
  docs/en/kmesh_use_enhanced_kernel.md
  docs/en/multiple_dataplane_EN.md
  docs/en/unit_test_doc.md
  docs/en/xds_handle.md
Labels: lgtm, approved, size/XS

#1483 Fix typo : Duel to Dual
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/question.md
  README.md
  docs/en/kmesh_support.md
Labels: lgtm, approved, size/S

#1487 feat(kmeshctl):automatic key generation for ipsec secrets
  ctl/secret/secret.go
  docs/ctl/kmeshctl.md
  docs/ctl/kmeshctl_secret.md
  docs/ctl/kmeshctl_secret_create.md
Labels: lgtm, approved, kind/feature, size/L
