Repository kmesh-net/kmesh, pull requests merged in 2025-02, with the labels that each got.

#1219 Fix typos
  deploy/README.md
  pkg/nets/nets.go
Labels: lgtm, approved, kind/cleanup, size/XS

#1217 Improve Authz UX: Immediate Feedback & Status Subcommand
  ctl/authz/authz.go
Labels: lgtm, approved, size/L

#1223 chore: solved contruct_tuple typo #1221
  bpf/kmesh/probes/tcp_probe.h
Labels: kind/enhancement, lgtm, approved, size/XS

#1241 Modify the kmeshctl documentation according to make gen
  docs/ctl/kmeshctl.md
  docs/ctl/kmeshctl_authz.md
  docs/ctl/kmeshctl_authz_disable.md
  docs/ctl/kmeshctl_authz_enable.md
  docs/ctl/kmeshctl_authz_status.md
Labels: lgtm, approved, size/M

#1244 add LiZhenCheng9527 to OWNERS
  OWNERS
Labels: lgtm, approved, size/XS

#1220 adapt BPF_LOG in route_config.h
  bpf/kmesh/ads/include/route_config.h
Labels: kind/enhancement, lgtm, approved, size/S

#1245 fix bookinfo issue 553
  bpf/kmesh/ads/include/route_config.h
Labels: lgtm, approved, size/S

#1248 add sample yamls for useguide
  samples/tcp-echo/tcp-echo-services.yaml
  samples/tcp-echo/tcp-echo-virtualservice.yaml
Labels: lgtm, approved, size/M

#1198 new kernel adapt
  bpf/include/bpf_helper_defs_ext.h
  bpf/kmesh/ads/cgroup_sock.c
  bpf/kmesh/ads/include/circuit_breaker.h
  bpf/kmesh/ads/include/filter.h
  bpf/kmesh/ads/include/kmesh_common.h
  bpf/kmesh/ads/include/route_config.h
  bpf/kmesh/ads/sockops.c
  bpf/kmesh/ads/tracepoint.c
  bpf/kmesh/bpf2go/bpf2go.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshtracepoint_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshtracepoint_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshtracepointcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshtracepointcompat_bpfel.go
  hack/golangci-lint-prepare.sh
  kernel/ko_src/kmesh/defer_connect.c
  kernel/ko_src/kmesh/defer_connect.h
  kernel/ko_src/kmesh/kmesh_main.c
  kernel/ko_src/kmesh/kmesh_parse_http_1_1.c
  kernel/ko_src/kmesh/kmesh_parse_protocol_data.c
  kernel/ko_src/kmesh/kmesh_parse_protocol_data.h
  kmesh_compile_env_pre.sh
  pkg/bpf/ads/loader_enhanced.go
  pkg/bpf/ads/sock_ops.go
  pkg/bpf/ads/trace_point.go
  pkg/controller/controller.go
  pkg/kolog/kolog.go
Labels: lgtm, approved, kind/feature, size/XXL
