Repository kmesh-net/kmesh, pull requests merged in 2025-07, with the labels that each got.

#1435 Fix: make format with too many containers
  .gitignore
  config/.gitignore
  hack/format.sh
  kmesh_compile_env_pre.sh
Labels: kind/enhancement, lgtm, approved, size/S

#1406 eBPF unit test: Remove expired codes & Add framework doc
  docs/ebpf_unit_test_zh.md
  test/unittest/workload/Makefile
  test/unittest/workload/common.h
  test/unittest/workload/run_tests.sh
  test/unittest/workload/xdp_test.c
Labels: kind/enhancement, lgtm, approved, size/XL

#1447 update golang.org/x/oauth2 to resolve Input vulnerability
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved, size/XS

#1448 fix markdownlint error
  docs/ebpf_unit_test_zh.md
Labels: lgtm, approved, size/XS
