Repository kmesh-net/kmesh, pull requests merged in 2025-03, with the labels that each got.

#1256 optimizie xdp auth
  bpf/kmesh/workload/include/authz.h
  bpf/kmesh/workload/xdp.c
Labels: lgtm, approved, size/S

#1268 adapt doc
  docs/kmesh_kernel_compile-zh.md
  docs/kmesh_kernel_compile.md
  docs/kmesh_support-zh.md
  docs/kmesh_use_enhanced_kernel.md
Labels: lgtm, approved, size/M

#1274 enable auth offload by default
  pkg/bpf/bpf.go
Labels: lgtm, approved, size/XS

#1224 Proposal for tcp_long_connection_metrics
  docs/proposal/tcp_long_connection_metrics.md
Labels: lgtm, approved, kind/feature, size/L

#1263 Make use of global variables instead of bpf config map
  bpf/include/common.h
  bpf/include/map_config.h
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkdecrypt_bpfeb.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkdecrypt_bpfel.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkdecryptcompat_bpfeb.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkdecryptcompat_bpfel.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkencrypt_bpfeb.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkencrypt_bpfel.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkencryptcompat_bpfeb.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkencryptcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockops_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockops_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockopscompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshsockopscompat_bpfel.go
  bpf/kmesh/probes/probe.h
  bpf/kmesh/workload/sockops.c
  bpf/kmesh/workload/xdp.c
  daemon/manager/manager.go
  pkg/bpf/ads/loader.go
  pkg/bpf/ads/loader_enhanced.go
  pkg/bpf/bpf.go
  pkg/bpf/bpf_test.go
  pkg/bpf/factory/factory.go
  pkg/bpf/workload/loader.go
  pkg/controller/controller.go
  pkg/status/status_server.go
  pkg/status/status_server_test.go
  pkg/utils/test/bpf_map.go
Labels: kind/enhancement, lgtm, approved, size/XXL

#1275 add channel for Rbac when Kmesh restart
  pkg/controller/workload/workload_controller.go
  pkg/controller/workload/workload_controller_test.go
  pkg/controller/workload/workload_processor.go
Labels: lgtm, approved, size/M

#1288 fix getKmeshWaypointImage tag
  ctl/waypoint/waypoint.go
Labels: kind/bug, lgtm, approved, size/XS

#1283 fix possible e2e panic and update maxportnum warning
  pkg/controller/workload/workload_processor.go
  test/e2e/gateway_test.go
Labels: kind/bug, lgtm, approved, size/XS

#1285 Remove spammy log
  bpf/include/bpf_log.h
Labels: lgtm, approved, size/XS

#1291 Fix bpf log level
  pkg/bpf/bpf.go
Labels: lgtm, approved, size/S
