Repository kmesh-net/kmesh, pull requests merged in 2025-01, with the labels that each got.

#1153 handle service and workload conflicts in the frontend map
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: kind/bug, lgtm, approved, size/M

#1145 make sure uts in different pkg cannot be run in parallel
  hack/run-ut.sh
Labels: lgtm, approved, size/XS

#1155 Clean up docker properly when ut fails
  hack/run-ut.sh
Labels: kind/enhancement, lgtm, approved, size/XS

#1156 add meeting in readme
  README.md
Labels: lgtm, approved, size/S

#1161 fix ebpf map elem nums grow abnormal
  bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
  pkg/bpf/ads/sock_connection.go
  pkg/cache/v2/listener_test.go
  pkg/utils/test/bpf_map.go
Labels: kind/bug, lgtm, approved, size/M

#1166 Filter unused authz
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: lgtm, approved, size/M

#1173 [release-1.0] update the VERSION to 1.0.0 in Makefile
  Makefile
Labels: lgtm, approved, size/XS

#1158 improve xdp bpf log
  bpf/kmesh/workload/include/authz.h
Labels: lgtm, approved, size/M

#1174 Ability to automatically push helm packages at publicize release
  .github/workflows/release.yml
Labels: lgtm, approved, size/XS

#1176 Can specify the out name for kmeshctl
  Makefile
Labels: lgtm, approved, size/XS

#1168 fix DATA RACE in TestCertRoute
  pkg/controller/security/manager_test.go
Labels: kind/bug, lgtm, approved, size/XS, cherrypick/release-1.0

#1182 [release-1.0] Change the version to v1.0.0-rc.0 in the makefile
  Makefile
Labels: lgtm, approved, size/XS

#1183 add scripts to change kmesh version automatically
  .github/workflows/release-master.yaml
  .github/workflows/release.yml
  Makefile
  hack/update-version.sh
Labels: kind/enhancement, lgtm, approved, size/L, cherrypick/release-1.0

#1187 adapt MAP_SIZE_OF_LISTENER into 8192
  bpf/kmesh/ads/include/config.h
Labels: lgtm, approved, kind/feature, size/XS

#1188 fix Update mode failed
  pkg/bpf/bpf.go
  pkg/constants/constants.go
Labels: kind/bug, lgtm, approved, size/XS, cherrypick/release-1.0

#1193 Bump golang.org/x/net to address CVE-2024-45338
  go.mod
  go.sum
Labels: lgtm, approved, size/S, cherrypick/release-1.0

#1195 bump golang.org/x/net to address CVE
  go.mod
  go.sum
Labels: lgtm, approved, kind/security, size/S

#1199 fix kernel_enhanced lack of pkg general
  pkg/bpf/ads/loader_enhanced.go
Labels: kind/bug, lgtm, approved, size/XS

#1197 bump version to 1.1-dev
  Makefile
Labels: lgtm, approved, size/XS

#1205 Bump github.com/cilium/ebpf from 0.16.0 to 0.17.1
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkdecrypt_bpfeb.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkdecrypt_bpfel.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkdecryptcompat_bpfeb.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkdecryptcompat_bpfel.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkencrypt_bpfeb.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkencrypt_bpfel.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkencryptcompat_bpfeb.go
  bpf/kmesh/bpf2go/general/kmeshtcmarkencryptcompat_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
  bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
  bpf/kmesh/workload/include/authz.h
  bpf/kmesh/workload/include/workload_common.h
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#1196 Update meeting in README.md
  README.md
Labels: lgtm, approved, size/XS

#1105 add workload metrics
  bpf/kmesh/probes/tcp_probe.h
  pkg/controller/telemetry/accesslog.go
  pkg/controller/telemetry/accesslog_test.go
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/utils.go
Labels: kind/enhancement, lgtm, approved, size/M
