Repository kmesh-net/kmesh, pull requests merged in 2025-09, with the labels that each got.

#1496 Resolving communication issue between pods after enabling IPsec
  bpf/kmesh/general/include/tc.h
  bpf/kmesh/general/tc_mark_decrypt.c
  pkg/constants/constants.go
  pkg/controller/encryption/ipsec/ipsec_handler.go
  test/bpf_ut/bpftest/general_test.go
  test/bpf_ut/tc_mark_decrypt_test.c
Labels: kind/bug, lgtm, approved, size/L

#1474 feat: add cgroup_skb eBPF program
  pkg/bpf/factory/factory.go
  test/bpf_ut/Makefile
  test/bpf_ut/bpftest/bpf_test.go
  test/bpf_ut/bpftest/workload_test.go
  test/bpf_ut/workload_cgroup_skb_test.c
Labels: lgtm, approved, size/L

#1498 feature(workflow): added Kmeshctl doc syncing workflow
  .github/workflows/sync-kmeshctl-docs.yml
Labels: kind/enhancement, lgtm, approved, kind/feature, size/M

#1452 ut_sendmsg
  bpf/kmesh/workload/sendmsg.c
  test/bpf_ut/Makefile
  test/bpf_ut/bpftest/bpf_test.go
  test/bpf_ut/bpftest/tlv_utils.go
  test/bpf_ut/bpftest/workload_test.go
  test/bpf_ut/build_bpf_ut_tests.sh
  test/bpf_ut/workload_sendmsg_test.c
Labels: lgtm, approved, do-not-merge/contains-merge-commits, size/XL

#1508 fix an error of kmeshctl waypoint
  ctl/waypoint/waypoint.go
  docs/ctl/kmeshctl_waypoint_apply.md
Labels: lgtm, approved, size/XS
