Repository kmesh-net/kmesh, pull requests merged in 2025-05, with the labels that each got.

#1329 bash format added in make format
  build.sh
  build/docker/start_kmesh.sh
  build/kmesh-start-pre.sh
  build/kmesh-stop-post.sh
  hack/copyright-check.sh
  hack/format.sh
  hack/gen-check.sh
  hack/gen_bpf2go.sh
  hack/gen_bpf2go_exec.sh
  hack/gen_protoc.sh
  hack/golangci-lint-prepare.sh
  hack/install-proto.sh
  hack/run-ebpf-ut.sh
  hack/run-ut.sh
  hack/update-version.sh
  hack/utils.sh
  kmesh_bpf_env.sh
  kmesh_compile_env_pre.sh
  kmesh_macros_env.sh
  kmesh_macros_env_kernel.sh
  pkg/kube/clean.sh
  pkg/kube/generate.sh
  test/e2e/run_test.sh
  test/performance/big_small_test/shell/test_big_small.sh
  test/performance/bookinfo_test/shell/bookinfo.sh
  test/performance/density_test/shell/density_test.sh
  test/performance/long_test/shell/long_test.sh
  test/performance/multiple_test/config/yaml/get_nginx_svc_address.sh
  test/performance/multiple_test/config/yaml/install.sh
  test/performance/multiple_test/config/yaml/uninstall.sh
  test/performance/multiple_test/shell/test_nginx.sh
  test/performance/packsize_test/shell/packsize_test.sh
  test/performance/qps_test/shell/qps_test.sh
  test/performance/short_test/shell/short_test.sh
  test/runtest.sh
  test/testcases/kmesh/libs/common.sh
  test/testcases/kmesh/oe_test_base_function/oe_test_base_function.sh
  test/testcases/kmesh/oe_test_dark_launch_function/oe_test_dark_launch_function.sh
  test/testcases/kmesh/oe_test_lb_policy_function/oe_test_lb_policy_function.sh
  test/testcases/kmesh/oe_test_route_function/oe_test_route_function.sh
  test/testcases/kmesh/oe_test_service_function/oe_test_service_function.sh
  test/testcases/kmesh/oe_test_tcp_proxy_weight_cluster_function/oe_test_tcp_proxy_weight_cluster_function.sh
  test/unittest/workload/run_tests.sh
Labels: kind/enhancement, lgtm, approved, do-not-merge/contains-merge-commits, size/XXL

#1359 Update quick-start link
  README.md
Labels: lgtm, approved, size/XS

#1360 added periodic report knob for long connection
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfel.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfeb.go
  bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfel.go
  bpf/kmesh/workload/cgroup_skb.c
  pkg/bpf/bpf.go
  pkg/status/status_server.go
Labels: lgtm, approved, kind/feature, size/M

#1361 eBPF unit test: add workload sockops ut
  hack/run-ebpf-ut.sh
  test/bpf_ut/Makefile
  test/bpf_ut/bpftest/bpf_test.go
  test/bpf_ut/bpftest/workload_test.go
  test/bpf_ut/workload_sockops_test.c
Labels: kind/enhancement, lgtm, approved, size/XL

#1351 remove BpfLoader.KmeshConfig to prevent writing using it, should alwa…
  pkg/bpf/bpf.go
Labels: kind/bug, lgtm, approved, size/L

#1362 eBPF unit test: add general tc ut
  bpf/kmesh/general/tc_mark_encrypt.c
  test/bpf_ut/Makefile
  test/bpf_ut/bpftest/bpf_test.go
  test/bpf_ut/bpftest/general_test.go
  test/bpf_ut/include/tc_common.h
  test/bpf_ut/tc_mark_decrypt_test.c
  test/bpf_ut/tc_mark_encrypt_test.c
Labels: kind/enhancement, lgtm, approved, size/L

#1363 fix log cannot print in kernel 5.10 by bpf_trace_printk
  bpf/kmesh/ads/include/cluster.h
  bpf/kmesh/workload/xdp.c
Labels: kind/bug, lgtm, approved, size/M

#1372 fix: enableConnMetric knob at monitoring handler
  pkg/status/status_server.go
Labels: kind/bug, lgtm, approved, size/S

#1368 Skip output accesslog on connection establishment
  docs/proposal/tcp_long_connection_metrics.md
  pkg/controller/telemetry/accesslog.go
  pkg/controller/telemetry/metric.go
Labels: kind/bug, lgtm, approved, size/S, cherrypick/release-1.1

#1376 rfac: outputAccesslog func to skip accesslog at conn establishment
  docs/proposal/tcp_long_connection_metrics.md
  pkg/controller/telemetry/accesslog.go
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
  pkg/controller/telemetry/utils.go
Labels: lgtm, approved, size/S

#1383 Fix: unexpected log when pod is shutting down
  bpf/kmesh/probes/probe.h
  bpf/kmesh/probes/tcp_probe.h
  pkg/controller/manage/manage_controller.go
Labels: lgtm, approved, size/M, cherrypick/release-1.1

#1371 fix kmeshctl version report error
  ctl/version/version.go
  ctl/version/version_test.go
Labels: kind/bug, lgtm, approved, size/M, cherrypick/release-1.1

#1365 e2e for l4 auth
  test/e2e/baseline_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1378 Fix regression by socket tuple when c/s deployed in same node
  pkg/controller/telemetry/accesslog.go
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
Labels: lgtm, approved, size/L, cherrypick/release-1.1

#1391 use bytes_acked instead of delivered to get the sent bytes, it is acc…
  bpf/kmesh/probes/tcp_probe.h
Labels: lgtm, approved, size/XS, cherrypick/release-1.1

#1395 Fix authz during shutdown
  bpf/kmesh/workload/include/frontend.h
  bpf/kmesh/workload/xdp.c
  pkg/controller/workload/workload_processor.go
  pkg/controller/workload/workload_processor_test.go
Labels: lgtm, approved, size/M, cherrypick/release-1.1

#1399 chore: ut coverage for same src/dst but different direction
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1404 Changed the metric name of grafana to match the metric name reported by kmesh
  samples/addons/grafana.yaml
  samples/addons/kmesh_performance-monitoring.json
Labels: kind/bug, lgtm, approved, size/XS

#1377 refactored updateConnectionMetricCache to report connection-metrics correctly
  pkg/controller/telemetry/metric.go
  pkg/controller/telemetry/metric_test.go
Labels: kind/bug, lgtm, approved, size/M

#1413 fix flaky of `TestCrossNamespace`
  pkg/controller/manage/manage_controller.go
Labels: kind/bug, lgtm, approved, size/S, cherrypick/release-1.1

#1405 add YaoZengzeng as owner
  OWNERS
Labels: lgtm, approved, size/XS

#1417 feat: add markdownlint for md documents
  .github/ISSUE_TEMPLATE/good-first.md
  .github/workflows/main.yml
  .github/workflows/markdownlint.yml
  .markdownlint.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README-zh.md
  README.md
  SECURITY.md
  bpf/kmesh/README.md
  build/docker/README.md
  deploy/README.md
  docs/Startup_process_of_eBPF_programs.md
  docs/ctl/kmeshctl_accesslog.md
  docs/dataplane_forward.md
  docs/kmesh_commands-zh.md
  docs/kmesh_commands.md
  docs/kmesh_compile-zh.md
  docs/kmesh_compile.md
  docs/kmesh_demo-zh.md
  docs/kmesh_demo.md
  docs/kmesh_deploy_and_develop_in_kind.md
  docs/kmesh_development_guide.md
  docs/kmesh_kernel_compile-zh.md
  docs/kmesh_kernel_compile.md
  docs/kmesh_performance.md
  docs/kmesh_support-zh.md
  docs/kmesh_use_enhanced_kernel.md
  docs/multiple dataplane_CN.md
  docs/multiple dataplane_EN.md
  docs/proposal/bypass.md
  docs/proposal/bypass_zh.md
  docs/proposal/circuit_breaker.md
  docs/proposal/dns_resolve.md
  docs/proposal/e2e.md
  docs/proposal/ebpf-observability.md
  docs/proposal/ebpf_unit_test.md
  docs/proposal/ebpf_unit_test_zh.md
  docs/proposal/kmesh_support_encrypt.md
  docs/proposal/kmesh_support_localityLB.md
  docs/proposal/kmesh_support_workload.md
  docs/proposal/local_ratelimit.md
  docs/proposal/map-in-map_management_enhancement-en.md
  docs/proposal/observability.md
  docs/proposal/optimizing_bpf_map_update_in_xDS_mode-en.md
  docs/proposal/performance_monitoring.md
  docs/proposal/tcp_long_connection_metrics.md
  docs/proposal/tls_cert.md
  docs/proposal/tls_cert_zh.md
  docs/unit_test_doc.md
  docs/xds_handle.md
  docs/xds_handle_zh.md
  hack/format.sh
  oncn-mda/README.md
  oncn-mda/docs/design.md
  test/README.md
  test/e2e/README.md
  test/performance/README-zh.md
  test/performance/README.md
Labels: kind/enhancement, lgtm, approved, size/XXL

#1393 output kmesh log when e2e test failed
  test/e2e/run_test.sh
Labels: kind/enhancement, lgtm, approved, size/L

#1421 Fix: wrong arg order of testify/assert
  pkg/cache/v2/listener_test.go
  pkg/controller/ads/ads_processor_test.go
  pkg/controller/ads/convert_filter_test.go
  pkg/controller/telemetry/metric_test.go
  pkg/controller/workload/bpfcache/endpoint_test.go
  pkg/controller/workload/cache/waypoint_cache_test.go
  pkg/controller/workload/workload_processor_test.go
  pkg/status/status_server_test.go
Labels: kind/bug, lgtm, approved, size/M

#1418 Fix: bump of containernetworking/plugins
  .github/workflows/main.yml
  go.mod
  go.sum
Labels: kind/enhancement, lgtm, approved, size/M

#1426 feat: add prepare-dev in Makefile
  Makefile
  api/Makefile
  hack/gen-protoc.sh
Labels: kind/enhancement, lgtm, approved, size/XS

#1419 Fix: make build should build kmeshctl
  Makefile
  hack/utils.sh
Labels: kind/enhancement, lgtm, approved, size/XS
